//! platform generated_138 — next 100 stubs EA-sorted desc high-EA filler continuation after 0xf67dc4
//! Filter: high-EA filler EA-sorted desc, rbx_core::SharedPtr not boost
//! Batch: 100 stubs EA-sorted desc | skeleton batch | range 0xf63e44..0xf67dc4 (rbx_core::SharedPtr not boost)

#![allow(non_snake_case, dead_code, unused_variables, unused_imports, clippy::all)]

use rbx_core::SharedPtr;

// 0xf67dc4 — j___ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_
// type: int __fastcall(int, int, struct _Unwind_Exception *lpuexcpt)
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_")]
pub fn stub_f67dc4() -> ! {
    todo!("0xf67dc4 j___ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_")
}

// 0xf67db4 — j___ZN4Ogre21MaterialScriptContextD2Ev
// type: void __fastcall(Ogre::MaterialScriptContext *__hidden this)
#[doc(alias = "j___ZN4Ogre21MaterialScriptContextD2Ev")]
pub fn stub_f67db4() -> ! {
    todo!("0xf67db4 j___ZN4Ogre21MaterialScriptContextD2Ev")
}

// 0xf651c4 — j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_
// type: _DWORD __fastcall(Ogre::ShaderScriptListener *__hidden this, const std::string *, const std::string *, const std::string *)
#[doc(alias = "j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_")]
pub fn stub_f651c4() -> ! {
    todo!("0xf651c4 j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_")
}

// 0xf651b4 — j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE
// type: _DWORD __fastcall(Ogre::ShaderScriptListener *__hidden this, const Ogre::CreateHighLevelGpuProgramScriptCompilerEvent *)
#[doc(alias = "j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE")]
pub fn stub_f651b4() -> ! {
    todo!("0xf651b4 j___ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE")
}

// 0xf64a64 — j___ZNSt4listIN5boost9unordered15iterator_detail8iteratorINS1_6detail8ptr_nodeISt4pairIKN3RBX12StreamRegion2IdENS7_7Network10RegionInfoEEEEEESaISF_EE4sortIPFbSF_SF_EEEvT_
// type: int __fastcall(std::_List_node_base *, int (__fastcall *)(_DWORD, _DWORD)) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(std::_List_node_base *, int (__fastcall *)(_DWORD, _DWORD))
#[doc(alias = "j___ZNSt4listIN5boost9unordered15iterator_detail8iteratorINS1_6detail8ptr_nodeISt4pairIKN3RBX12StreamRegion2IdENS7_7Network10RegionInfoEEEEEESaISF_EE4sortIPFbSF_SF_EEEvT_")]
pub fn stub_f64a64() -> ! {
    todo!("0xf64a64 j___ZNSt4listIN5boost9unordered15iterator_detail8iteratorINS1_6detail8ptr_nodeISt4pairIKN3RBX12StreamRegion2IdENS7_7Network10RegionInfoEEEEEESaISF_EE4sortIPFbSF_SF_EEEvT_")
}

// 0xf64a54 — j___ZNK5boost4_mfi3mf2IvN3RBX7Network16ClientReplicatorESt6vectorIPNS2_12PartInstanceESaIS7_EENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S9_SC_
// type: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZNK5boost4_mfi3mf2IvN3RBX7Network16ClientReplicatorESt6vectorIPNS2_12PartInstanceESaIS7_EENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S9_SC_")]
pub fn stub_f64a54() -> ! {
    todo!("0xf64a54 j___ZNK5boost4_mfi3mf2IvN3RBX7Network16ClientReplicatorESt6vectorIPNS2_12PartInstanceESaIS7_EENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S9_SC_")
}

// 0xf64a44 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_")]
pub fn stub_f64a44() -> ! {
    todo!("0xf64a44 j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_")
}

// 0xf64a34 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJob17RegionRemovalItemENS_10shared_ptrINS2_8InstanceEEEEclEPS6_S9_
// type: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJob17RegionRemovalItemENS_10shared_ptrINS2_8InstanceEEEEclEPS6_S9_")]
pub fn stub_f64a34() -> ! {
    todo!("0xf64a34 j___ZNK5boost4_mfi3mf1IvN3RBX7Network16ClientReplicator5GCJob17RegionRemovalItemENS_10shared_ptrINS2_8InstanceEEEEclEPS6_S9_")
}

// 0xf64a24 — j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network16ClientReplicatorESt6vectorIPNS_12PartInstanceESaISB_EENS2_10shared_ptrIS0_EEEENS3_5list3INS3_5valueIPS8_EENSI_ISD_EENS2_3argILi1EEEEEEEEEvRKT_
// type: void __fastcall(int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(int, int)
#[doc(alias = "j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network16ClientReplicatorESt6vectorIPNS_12PartInstanceESaISB_EENS2_10shared_ptrIS0_EEEENS3_5list3INS3_5valueIPS8_EENSI_ISD_EENS2_3argILi1EEEEEEEEEvRKT_")]
pub fn stub_f64a24() -> ! {
    todo!("0xf64a24 j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network16ClientReplicatorESt6vectorIPNS_12PartInstanceESaISB_EENS2_10shared_ptrIS0_EEEENS3_5list3INS3_5valueIPS8_EENSI_ISD_EENS2_3argILi1EEEEEEEEEvRKT_")
}

// 0xf64a14 — j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJob17RegionRemovalItemENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPSA_EENS2_3argILi1EEEEEEEEEvRKT_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJob17RegionRemovalItemENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPSA_EENS2_3argILi1EEEEEEEEEvRKT_")]
pub fn stub_f64a14() -> ! {
    todo!("0xf64a14 j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJob17RegionRemovalItemENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPSA_EENS2_3argILi1EEEEEEEEEvRKT_")
}

// 0xf64a04 — j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJobENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS9_EENS2_3argILi1EEEEEEEEEvRKT_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJobENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS9_EENS2_3argILi1EEEEEEEEEvRKT_")]
pub fn stub_f64a04() -> ! {
    todo!("0xf64a04 j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvNS_7Network16ClientReplicator5GCJobENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS9_EENS2_3argILi1EEEEEEEEEvRKT_")
}

// 0xf649e4 — j___ZNK3RBX12StreamRegion9IdExtents19intersectsContainerIN5boost9unordered13unordered_mapINS0_2IdENS_7Network10RegionInfoENS6_27boost_compatible_hash_valueESt8equal_toIS6_ESaISt4pairIKS6_S8_EEEEEEbRKT_PS6_
// type: int __fastcall(int *, int, _DWORD *) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int *, int, _DWORD *)
#[doc(alias = "j___ZNK3RBX12StreamRegion9IdExtents19intersectsContainerIN5boost9unordered13unordered_mapINS0_2IdENS_7Network10RegionInfoENS6_27boost_compatible_hash_valueESt8equal_toIS6_ESaISt4pairIKS6_S8_EEEEEEbRKT_PS6_")]
pub fn stub_f649e4() -> ! {
    todo!("0xf649e4 j___ZNK3RBX12StreamRegion9IdExtents19intersectsContainerIN5boost9unordered13unordered_mapINS0_2IdENS_7Network10RegionInfoENS6_27boost_compatible_hash_valueESt8equal_toIS6_ESaISt4pairIKS6_S8_EEEEEEbRKT_PS6_")
}

// 0xf649d4 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm")]
pub fn stub_f649d4() -> ! {
    todo!("0xf649d4 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm")
}

// 0xf649c4 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm")]
pub fn stub_f649c4() -> ! {
    todo!("0xf649c4 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm")
}

// 0xf649b4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE9erase_keyERS8_
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE9erase_keyERS8_")]
pub fn stub_f649b4() -> ! {
    todo!("0xf649b4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE9erase_keyERS8_")
}

// 0xf649a4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE12emplace_implINS1_13emplace_args1ISB_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISB_EEEEbERS8_RKT_
// type: int __fastcall(_DWORD *, _DWORD *, _DWORD *, _QWORD **) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD *, _DWORD *, _DWORD *, _QWORD **)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE12emplace_implINS1_13emplace_args1ISB_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISB_EEEEbERS8_RKT_")]
pub fn stub_f649a4() -> ! {
    todo!("0xf649a4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network10RegionInfoEEES7_SA_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE12emplace_implINS1_13emplace_args1ISB_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISB_EEEEbERS8_RKT_")
}

// 0xf64994 — j___ZN5boost4bindIvN3RBX7Network16ClientReplicatorESt6vectorIPNS1_12PartInstanceESaIS6_EENS_10shared_ptrINS1_8InstanceEEEPS3_S8_NS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf2ISH_T0_T1_T2_EENSF_9list_av_3IT3_T4_T5_E4typeEEEMSK_FSH_SL_SM_ESP_SQ_SR_
// type: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN5boost4bindIvN3RBX7Network16ClientReplicatorESt6vectorIPNS1_12PartInstanceESaIS6_EENS_10shared_ptrINS1_8InstanceEEEPS3_S8_NS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf2ISH_T0_T1_T2_EENSF_9list_av_3IT3_T4_T5_E4typeEEEMSK_FSH_SL_SM_ESP_SQ_SR_")]
pub fn stub_f64994() -> ! {
    todo!("0xf64994 j___ZN5boost4bindIvN3RBX7Network16ClientReplicatorESt6vectorIPNS1_12PartInstanceESaIS6_EENS_10shared_ptrINS1_8InstanceEEEPS3_S8_NS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf2ISH_T0_T1_T2_EENSF_9list_av_3IT3_T4_T5_E4typeEEEMSK_FSH_SL_SM_ESP_SQ_SR_")
}

// 0xf64984 — j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEclINS_4_mfi3mf2IvS5_SC_NS_10shared_ptrINS3_8InstanceEEEEENS0_5list1IRKSM_EEEEvNS0_4typeIvEERT_RT0_i
// type: int __fastcall(_DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEclINS_4_mfi3mf2IvS5_SC_NS_10shared_ptrINS3_8InstanceEEEEENS0_5list1IRKSM_EEEEvNS0_4typeIvEERT_RT0_i")]
pub fn stub_f64984() -> ! {
    todo!("0xf64984 j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEclINS_4_mfi3mf2IvS5_SC_NS_10shared_ptrINS3_8InstanceEEEEENS0_5list1IRKSM_EEEEvNS0_4typeIvEERT_RT0_i")
}

// 0xf64974 — j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEC2ES7_SD_SF_
// type: int __fastcall(_DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEC2ES7_SD_SF_")]
pub fn stub_f64974() -> ! {
    todo!("0xf64974 j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network16ClientReplicatorEEENS2_ISt6vectorIPNS3_12PartInstanceESaISA_EEEENS_3argILi1EEEEC2ES7_SD_SF_")
}

// 0xf64944 — j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE5eraseESt15_Deque_iteratorIS5_RS5_PS5_E
// type: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE5eraseESt15_Deque_iteratorIS5_RS5_PS5_E")]
pub fn stub_f64944() -> ! {
    todo!("0xf64944 j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE5eraseESt15_Deque_iteratorIS5_RS5_PS5_E")
}

// 0xf64934 — j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_reallocate_mapEmb
// type: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_reallocate_mapEmb")]
pub fn stub_f64934() -> ! {
    todo!("0xf64934 j___ZNSt5dequeIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_reallocate_mapEmb")
}

// 0xf64914 — j___ZNSt11_Deque_baseIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_initialize_mapEm
// type: int __fastcall(int, int, int, int, int, int, int, int, void *, int)
#[doc(alias = "j___ZNSt11_Deque_baseIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_initialize_mapEm")]
pub fn stub_f64914() -> ! {
    todo!("0xf64914 j___ZNSt11_Deque_baseIPN3RBX7Network10Replicator9StreamJob14StreamDataItemESaIS5_EE17_M_initialize_mapEm")
}

// 0xf64904 — j___ZNK5boost4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEPNS5_14StreamDataItemEEclEPS5_S8_SA_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEPNS5_14StreamDataItemEEclEPS5_S8_SA_")]
pub fn stub_f64904() -> ! {
    todo!("0xf64904 j___ZNK5boost4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEPNS5_14StreamDataItemEEclEPS5_S8_SA_")
}

// 0xf648f4 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_")]
pub fn stub_f648f4() -> ! {
    todo!("0xf648f4 j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS2_8InstanceEEEEclEPS5_S8_")
}

// 0xf648d4 — j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10Replicator9StreamJobENS2_10shared_ptrIS0_EEPNS9_14StreamDataItemEEENS3_5list3INS3_5valueIPS9_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, int, int, int, int)
#[doc(alias = "j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10Replicator9StreamJobENS2_10shared_ptrIS0_EEPNS9_14StreamDataItemEEENS3_5list3INS3_5valueIPS9_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_")]
pub fn stub_f648d4() -> ! {
    todo!("0xf648d4 j___ZNK3RBX8Instance16visitDescendantsIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10Replicator9StreamJobENS2_10shared_ptrIS0_EEPNS9_14StreamDataItemEEENS3_5list3INS3_5valueIPS9_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_")
}

// 0xf64864 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS5_7Network10Replicator15ReplicationDataEEES8_SC_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISD_EESN_
// type: void __fastcall(_DWORD *, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS5_7Network10Replicator15ReplicationDataEEES8_SC_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISD_EESN_")]
pub fn stub_f64864() -> ! {
    todo!("0xf64864 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS5_7Network10Replicator15ReplicationDataEEES8_SC_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISD_EESN_")
}

// 0xf64854 — j___ZN5boost3_bi6bind_tIvNS_4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS4_8InstanceEEEPNS7_14StreamDataItemEEENS0_5list3INS0_5valueIPS7_EENS_3argILi1EEENSF_ISC_EEEEEclISA_EEvRKT_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZN5boost3_bi6bind_tIvNS_4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS4_8InstanceEEEPNS7_14StreamDataItemEEENS0_5list3INS0_5valueIPS7_EENS_3argILi1EEENSF_ISC_EEEEEclISA_EEvRKT_")]
pub fn stub_f64854() -> ! {
    todo!("0xf64854 j___ZN5boost3_bi6bind_tIvNS_4_mfi3mf2IvN3RBX7Network10Replicator9StreamJobENS_10shared_ptrINS4_8InstanceEEEPNS7_14StreamDataItemEEENS0_5list3INS0_5valueIPS7_EENS_3argILi1EEENSF_ISC_EEEEEclISA_EEvRKT_")
}

// 0xf64794 — j___ZN5boost9unordered6detail10table_implINS1_3mapINS_19fast_pool_allocatorIN3RBX10Reflection13ConstPropertyENS_33default_user_allocator_new_deleteENS_5mutexELj32ELj0EEES7_NS_9intrusive13list_iteratorINSB_9list_implINSB_7listoptINSB_6detail16base_hook_traitsINS5_7Network4ItemENSB_16list_node_traitsIPvEELNSB_14link_mode_typeE1ENSH_7ItemTagELi1EEEmLb1EEEEELb0EEENS_4hashIS7_EESt8equal_toIS7_EEEE9erase_keyERKS7_
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapINS_19fast_pool_allocatorIN3RBX10Reflection13ConstPropertyENS_33default_user_allocator_new_deleteENS_5mutexELj32ELj0EEES7_NS_9intrusive13list_iteratorINSB_9list_implINSB_7listoptINSB_6detail16base_hook_traitsINS5_7Network4ItemENSB_16list_node_traitsIPvEELNSB_14link_mode_typeE1ENSH_7ItemTagELi1EEEmLb1EEEEELb0EEENS_4hashIS7_EESt8equal_toIS7_EEEE9erase_keyERKS7_")]
pub fn stub_f64794() -> ! {
    todo!("0xf64794 j___ZN5boost9unordered6detail10table_implINS1_3mapINS_19fast_pool_allocatorIN3RBX10Reflection13ConstPropertyENS_33default_user_allocator_new_deleteENS_5mutexELj32ELj0EEES7_NS_9intrusive13list_iteratorINSB_9list_implINSB_7listoptINSB_6detail16base_hook_traitsINS5_7Network4ItemENSB_16list_node_traitsIPvEELNSB_14link_mode_typeE1ENSH_7ItemTagELi1EEEmLb1EEEEELb0EEENS_4hashIS7_EESt8equal_toIS7_EEEE9erase_keyERKS7_")
}

// 0xf64784 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm")]
pub fn stub_f64784() -> ! {
    todo!("0xf64784 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE18reserve_for_insertEm")
}

// 0xf64774 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm")]
pub fn stub_f64774() -> ! {
    todo!("0xf64774 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEE14create_bucketsEm")
}

// 0xf64764 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEEixERS8_
// type: _QWORD *__fastcall(_DWORD *, _DWORD *) — uses boost, now rbx_core::SharedPtr
// was: _QWORD *__fastcall(_DWORD *, _DWORD *)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEEixERS8_")]
pub fn stub_f64764() -> ! {
    todo!("0xf64764 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKN3RBX12StreamRegion2IdENS5_7Network18ClusterPacketCache15CachedBitStreamEEES7_SB_NS7_27boost_compatible_hash_valueESt8equal_toIS7_EEEEixERS8_")
}

// 0xf646d4 — j___ZN3RBX7Network18ClusterPacketCacheD2Ev
// type: void __fastcall(RBX::Network::ClusterPacketCache *__hidden this)
#[doc(alias = "j___ZN3RBX7Network18ClusterPacketCacheD2Ev")]
pub fn stub_f646d4() -> ! {
    todo!("0xf646d4 j___ZN3RBX7Network18ClusterPacketCacheD2Ev")
}

// 0xf646a4 — j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network23ErrorCompPhysicsSender2ERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_
// type: int __fastcall(_DWORD *, void *, void *, char *, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD *, void *, void *, char *, int, int)
#[doc(alias = "j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network23ErrorCompPhysicsSender2ERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_")]
pub fn stub_f646a4() -> ! {
    todo!("0xf646a4 j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network23ErrorCompPhysicsSender2ERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_")
}

// 0xf64694 — j___ZSt24__uninitialized_copy_auxIPN3RBX7Network23ErrorCompPhysicsSender26BucketES4_ET0_T_S6_S5_St12__false_type
// type: int __fastcall(int, int, int, int, void *, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int)
#[doc(alias = "j___ZSt24__uninitialized_copy_auxIPN3RBX7Network23ErrorCompPhysicsSender26BucketES4_ET0_T_S6_S5_St12__false_type")]
pub fn stub_f64694() -> ! {
    todo!("0xf64694 j___ZSt24__uninitialized_copy_auxIPN3RBX7Network23ErrorCompPhysicsSender26BucketES4_ET0_T_S6_S5_St12__false_type")
}

// 0xf64684 — j___ZNSt6vectorIN3RBX7Network23ErrorCompPhysicsSender26BucketESaIS3_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS3_S5_EERKS3_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, void *, int, int, int, int, int, int, int, void *, int, int, int, int, int, void *, int)
#[doc(alias = "j___ZNSt6vectorIN3RBX7Network23ErrorCompPhysicsSender26BucketESaIS3_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS3_S5_EERKS3_")]
pub fn stub_f64684() -> ! {
    todo!("0xf64684 j___ZNSt6vectorIN3RBX7Network23ErrorCompPhysicsSender26BucketESaIS3_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS3_S5_EERKS3_")
}

// 0xf64664 — j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EEaSERKS5_
// type: _DWORD *__fastcall(_DWORD *, _DWORD *)
#[doc(alias = "j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EEaSERKS5_")]
pub fn stub_f64664() -> ! {
    todo!("0xf64664 j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EEaSERKS5_")
}

// 0xf64654 — j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE9_M_insertESt14_List_iteratorIS3_ERKS3_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int)
#[doc(alias = "j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE9_M_insertESt14_List_iteratorIS3_ERKS3_")]
pub fn stub_f64654() -> ! {
    todo!("0xf64654 j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE9_M_insertESt14_List_iteratorIS3_ERKS3_")
}

// 0xf64644 — j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE6insertISt20_List_const_iteratorIS3_EEEvSt14_List_iteratorIS3_ET_SB_
// type: int __fastcall(int, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE6insertISt20_List_const_iteratorIS3_EEEvSt14_List_iteratorIS3_ET_SB_")]
pub fn stub_f64644() -> ! {
    todo!("0xf64644 j___ZNSt4listIN3RBX7Network23ErrorCompPhysicsSender26NuggetESaIS3_EE6insertISt20_List_const_iteratorIS3_EEEvSt14_List_iteratorIS3_ET_SB_")
}

// 0xf64634 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")]
pub fn stub_f64634() -> ! {
    todo!("0xf64634 j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")
}

// 0xf64624 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_12PartInstanceEEEEclEPS4_S7_
// type: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_12PartInstanceEEEEclEPS4_S7_")]
pub fn stub_f64624() -> ! {
    todo!("0xf64624 j___ZNK5boost4_mfi3mf1IvN3RBX7Network23ErrorCompPhysicsSender2ENS_10shared_ptrINS2_12PartInstanceEEEEclEPS4_S7_")
}

// 0xf64614 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE18reserve_for_insertEm
// type: int(void) — uses boost, now rbx_core::SharedPtr
// was: int(void)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE18reserve_for_insertEm")]
pub fn stub_f64614() -> ! {
    todo!("0xf64614 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE18reserve_for_insertEm")
}

// 0xf64604 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE14create_bucketsEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE14create_bucketsEm")]
pub fn stub_f64604() -> ! {
    todo!("0xf64604 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE14create_bucketsEm")
}

// 0xf645f4 — j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEEEEE20construct_with_valueINS1_13emplace_args1ISH_EEEEvRKT_
// type: int __fastcall(int, _DWORD **) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _DWORD **)
#[doc(alias = "j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEEEEE20construct_with_valueINS1_13emplace_args1ISH_EEEEvRKT_")]
pub fn stub_f645f4() -> ! {
    todo!("0xf645f4 j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEEEEE20construct_with_valueINS1_13emplace_args1ISH_EEEEvRKT_")
}

// 0xf645e4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE12emplace_implINS1_13emplace_args1ISH_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISH_EEEEbERSA_RKT_
// type: void __fastcall(_DWORD *, _DWORD *, unsigned int *, int, void *, char, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, _DWORD *, unsigned int *, int, void *, char, int, int, int, int)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE12emplace_implINS1_13emplace_args1ISH_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISH_EEEEbERSA_RKT_")]
pub fn stub_f645e4() -> ! {
    todo!("0xf645e4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE12emplace_implINS1_13emplace_args1ISH_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISH_EEEEbERSA_RKT_")
}

// 0xf645d4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE11erase_nodesEPNS1_8ptr_nodeISH_EESR_
// type: int __fastcall(_DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE11erase_nodesEPNS1_8ptr_nodeISH_EESR_")]
pub fn stub_f645d4() -> ! {
    todo!("0xf645d4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKNS_10shared_ptrIKN3RBX12PartInstanceEEESt14_List_iteratorISB_INS6_7Network23ErrorCompPhysicsSender26NuggetEEEEES9_SG_NS_4hashIS9_EESt8equal_toIS9_EEEE11erase_nodesEPNS1_8ptr_nodeISH_EESR_")
}

// 0xf645c4 — j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network18PhysicsPacketCacheERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_
// type: int __fastcall(int, void *, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, void *, int, int, int, int)
#[doc(alias = "j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network18PhysicsPacketCacheERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_")]
pub fn stub_f645c4() -> ! {
    todo!("0xf645c4 j___ZSt8for_eachIN3RBX9Intrusive3SetINS0_12PartInstanceENS0_14PhysicsServiceEE8IteratorEN5boost3_bi6bind_tIvNS7_4_mfi3mf1IvNS0_7Network18PhysicsPacketCacheERS3_EENS8_5list2INS8_5valueIPSD_EENS7_3argILi1EEEEEEEET0_T_SP_SO_")
}

// 0xf64594 — j___ZNK5boost4_mfi3mf2IvN3RBX7Network19InstancePacketCacheENS_10shared_ptrINS2_8InstanceEEES7_EclEPS4_S7_S7_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf2IvN3RBX7Network19InstancePacketCacheENS_10shared_ptrINS2_8InstanceEEES7_EclEPS4_S7_S7_")]
pub fn stub_f64594() -> ! {
    todo!("0xf64594 j___ZNK5boost4_mfi3mf2IvN3RBX7Network19InstancePacketCacheENS_10shared_ptrINS2_8InstanceEEES7_EclEPS4_S7_S7_")
}

// 0xf64584 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network18PhysicsPacketCacheENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network18PhysicsPacketCacheENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")]
pub fn stub_f64584() -> ! {
    todo!("0xf64584 j___ZNK5boost4_mfi3mf1IvN3RBX7Network18PhysicsPacketCacheENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")
}

// 0xf64574 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm
// type: int(void) — uses boost, now rbx_core::SharedPtr
// was: int(void)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm")]
pub fn stub_f64574() -> ! {
    todo!("0xf64574 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm")
}

// 0xf64564 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm
// type: unsigned int __fastcall(int, unsigned int) — uses boost, now rbx_core::SharedPtr
// was: unsigned int __fastcall(int, unsigned int)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm")]
pub fn stub_f64564() -> ! {
    todo!("0xf64564 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm")
}

// 0xf64554 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm
// type: int(void) — uses boost, now rbx_core::SharedPtr
// was: int(void)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm")]
pub fn stub_f64554() -> ! {
    todo!("0xf64554 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE18reserve_for_insertEm")
}

// 0xf64544 — j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm")]
pub fn stub_f64544() -> ! {
    todo!("0xf64544 j___ZN5boost9unordered6detail5tableINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE14create_bucketsEm")
}

// 0xf64534 — j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_")]
pub fn stub_f64534() -> ! {
    todo!("0xf64534 j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_")
}

// 0xf64524 — j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_
// type: int __fastcall(int, _DWORD **) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _DWORD **)
#[doc(alias = "j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_")]
pub fn stub_f64524() -> ! {
    todo!("0xf64524 j___ZN5boost9unordered6detail16node_constructorISaINS1_8ptr_nodeISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEEEEE20construct_with_valueINS1_13emplace_args1ISF_EEEEvRKT_")
}

// 0xf64514 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_
// type: int __fastcall(int, int, int, int, void *, char, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, void *, char, int, int, int, int)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_")]
pub fn stub_f64514() -> ! {
    todo!("0xf64514 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_")
}

// 0xf64504 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISF_EESP_
// type: int __fastcall(_DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISF_EESP_")]
pub fn stub_f64504() -> ! {
    todo!("0xf64504 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8InstanceENS_10shared_ptrINS5_7Network19InstancePacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE11erase_nodesEPNS1_8ptr_nodeISF_EESP_")
}

// 0xf644f4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE9erase_keyERS9_
// type: int __fastcall(_DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE9erase_keyERS9_")]
pub fn stub_f644f4() -> ! {
    todo!("0xf644f4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE9erase_keyERS9_")
}

// 0xf644e4 — j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_
// type: void __fastcall(_DWORD *, _DWORD *, unsigned int *, int, void *, char, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, _DWORD *, unsigned int *, int, void *, char, int, int, int, int)
#[doc(alias = "j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_")]
pub fn stub_f644e4() -> ! {
    todo!("0xf644e4 j___ZN5boost9unordered6detail10table_implINS1_3mapISaISt4pairIKPKN3RBX8AssemblyENS_10shared_ptrINS5_7Network18PhysicsPacketCache15CachedBitStreamEEEEES8_SE_NS_4hashIS8_EESt8equal_toIS8_EEEE12emplace_implINS1_13emplace_args1ISF_EEEES4_INS0_15iterator_detail8iteratorINS1_8ptr_nodeISF_EEEEbERS9_RKT_")
}

// 0xf644d4 — j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network19InstancePacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE
// type: int __fastcall(int, int, int, int, void *, int, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, void *, int, int, int, void *, int)
#[doc(alias = "j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network19InstancePacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE")]
pub fn stub_f644d4() -> ! {
    todo!("0xf644d4 j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network19InstancePacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE")
}

// 0xf644c4 — j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network18PhysicsPacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE
// type: int __fastcall(int, int, int, int, void *, int, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, void *, int, int, int, void *, int)
#[doc(alias = "j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network18PhysicsPacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE")]
pub fn stub_f644c4() -> ! {
    todo!("0xf644c4 j___ZN5boost6detail20sp_pointer_constructIN3RBX7Network18PhysicsPacketCache15CachedBitStreamES5_EEvPNS_10shared_ptrIT_EEPT0_RNS0_12shared_countE")
}

// 0xf644b4 — j___ZN5boost4bindIvN3RBX7Network19InstancePacketCache15CachedBitStreamEPKNS1_10Reflection18PropertyDescriptorENS_10shared_ptrIS4_EENS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf1ISF_T0_T1_EENSD_9list_av_2IT2_T3_E4typeEEEMSI_FSF_SJ_ESM_SN_
// type: int __fastcall(int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int)
#[doc(alias = "j___ZN5boost4bindIvN3RBX7Network19InstancePacketCache15CachedBitStreamEPKNS1_10Reflection18PropertyDescriptorENS_10shared_ptrIS4_EENS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf1ISF_T0_T1_EENSD_9list_av_2IT2_T3_E4typeEEEMSI_FSF_SJ_ESM_SN_")]
pub fn stub_f644b4() -> ! {
    todo!("0xf644b4 j___ZN5boost4bindIvN3RBX7Network19InstancePacketCache15CachedBitStreamEPKNS1_10Reflection18PropertyDescriptorENS_10shared_ptrIS4_EENS_3argILi1EEEEENS_3_bi6bind_tIT_NS_4_mfi3mf1ISF_T0_T1_EENSD_9list_av_2IT2_T3_E4typeEEEMSI_FSF_SJ_ESM_SN_")
}

// 0xf644a4 — j___ZN5boost3_bi8storage2INS0_5valueINS_10shared_ptrIN3RBX7Network19InstancePacketCache15CachedBitStreamEEEEENS_3argILi1EEEEC2ES9_SB_
// type: _DWORD *__fastcall(_DWORD *, unsigned int *, int, int, pthread_mutex_t *, int, struct _Unwind_Exception *lpuexcpt, int, int, pthread_mutex_t *, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: _DWORD *__fastcall(_DWORD *, unsigned int *, int, int, pthread_mutex_t *, int, struct _Unwind_Exception *lpuexcpt, int, int, pthread_mutex_t *, int, int, int, int)
#[doc(alias = "j___ZN5boost3_bi8storage2INS0_5valueINS_10shared_ptrIN3RBX7Network19InstancePacketCache15CachedBitStreamEEEEENS_3argILi1EEEEC2ES9_SB_")]
pub fn stub_f644a4() -> ! {
    todo!("0xf644a4 j___ZN5boost3_bi8storage2INS0_5valueINS_10shared_ptrIN3RBX7Network19InstancePacketCache15CachedBitStreamEEEEENS_3argILi1EEEEC2ES9_SB_")
}

// 0xf64494 — j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network19InstancePacketCacheEEENS_3argILi1EEENS8_ILi2EEEEclINS_4_mfi3mf2IvS5_NS_10shared_ptrINS3_8InstanceEEESH_EENS0_5list2IRSH_SK_EEEEvNS0_4typeIvEERT_RT0_i
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network19InstancePacketCacheEEENS_3argILi1EEENS8_ILi2EEEEclINS_4_mfi3mf2IvS5_NS_10shared_ptrINS3_8InstanceEEESH_EENS0_5list2IRSH_SK_EEEEvNS0_4typeIvEERT_RT0_i")]
pub fn stub_f64494() -> ! {
    todo!("0xf64494 j___ZN5boost3_bi5list3INS0_5valueIPN3RBX7Network19InstancePacketCacheEEENS_3argILi1EEENS8_ILi2EEEEclINS_4_mfi3mf2IvS5_NS_10shared_ptrINS3_8InstanceEEESH_EENS0_5list2IRSH_SK_EEEEvNS0_4typeIvEERT_RT0_i")
}

// 0xf643e4 — j___ZN3rbx8callableINS_7signals6signalIFvPKN3RBX10Reflection18PropertyDescriptorEEE4slotEN5boost3_bi6bind_tIvNSB_4_mfi3mf1IvNS3_7Network19InstancePacketCache15CachedBitStreamES7_EENSC_5list2INSC_5valueINSB_10shared_ptrISI_EEEENSB_3argILi1EEEEEEELi1ES8_ED2Ev
// type: _DWORD *__fastcall(_DWORD *) — uses boost, now rbx_core::SharedPtr
// was: _DWORD *__fastcall(_DWORD *)
#[doc(alias = "j___ZN3rbx8callableINS_7signals6signalIFvPKN3RBX10Reflection18PropertyDescriptorEEE4slotEN5boost3_bi6bind_tIvNSB_4_mfi3mf1IvNS3_7Network19InstancePacketCache15CachedBitStreamES7_EENSC_5list2INSC_5valueINSB_10shared_ptrISI_EEEENSB_3argILi1EEEEEEELi1ES8_ED2Ev")]
pub fn stub_f643e4() -> ! {
    todo!("0xf643e4 j___ZN3rbx8callableINS_7signals6signalIFvPKN3RBX10Reflection18PropertyDescriptorEEE4slotEN5boost3_bi6bind_tIvNSB_4_mfi3mf1IvNS3_7Network19InstancePacketCache15CachedBitStreamES7_EENSC_5list2INSC_5valueINSB_10shared_ptrISI_EEEENSB_3argILi1EEEEEEELi1ES8_ED2Ev")
}

// 0xf64394 — j___ZN3RBX11IndexedTree23visitConstMeAndChildrenINS_8AssemblyEN5boost3_bi6bind_tIvNS3_4_mfi3mf1IvNS_7Network18PhysicsPacketCacheEPKS2_EENS4_5list2INS4_5valueIPS9_EENS3_3argILi1EEEEEEEEEvT0_
// type: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZN3RBX11IndexedTree23visitConstMeAndChildrenINS_8AssemblyEN5boost3_bi6bind_tIvNS3_4_mfi3mf1IvNS_7Network18PhysicsPacketCacheEPKS2_EENS4_5list2INS4_5valueIPS9_EENS3_3argILi1EEEEEEEEEvT0_")]
pub fn stub_f64394() -> ! {
    todo!("0xf64394 j___ZN3RBX11IndexedTree23visitConstMeAndChildrenINS_8AssemblyEN5boost3_bi6bind_tIvNS3_4_mfi3mf1IvNS_7Network18PhysicsPacketCacheEPKS2_EENS4_5list2INS4_5valueIPS9_EENS3_3argILi1EEEEEEEEEvT0_")
}

// 0xf64304 — j___ZSt24__uninitialized_copy_auxISt15_Deque_iteratorIN5boost10shared_ptrIN3RBX7Network6MarkerEEERKS6_PS7_ES0_IS6_RS6_PS6_EET0_T_SF_SE_St12__false_type
// type: int __fastcall(int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, void *, int)
#[doc(alias = "j___ZSt24__uninitialized_copy_auxISt15_Deque_iteratorIN5boost10shared_ptrIN3RBX7Network6MarkerEEERKS6_PS7_ES0_IS6_RS6_PS6_EET0_T_SF_SE_St12__false_type")]
pub fn stub_f64304() -> ! {
    todo!("0xf64304 j___ZSt24__uninitialized_copy_auxISt15_Deque_iteratorIN5boost10shared_ptrIN3RBX7Network6MarkerEEERKS6_PS7_ES0_IS6_RS6_PS6_EET0_T_SF_SE_St12__false_type")
}

// 0xf64244 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E
// type: void __fastcall(int, _DWORD *) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(int, _DWORD *)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")]
pub fn stub_f64244() -> ! {
    todo!("0xf64244 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")
}

// 0xf64234 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_
// type: int __fastcall(int, _Rb_tree_node_base *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _Rb_tree_node_base *, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")]
pub fn stub_f64234() -> ! {
    todo!("0xf64234 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")
}

// 0xf64224 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_
// type: int __fastcall(int, _DWORD *, unsigned int *M_color, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _DWORD *, unsigned int *M_color, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")]
pub fn stub_f64224() -> ! {
    todo!("0xf64224 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")
}

// 0xf64214 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")]
pub fn stub_f64214() -> ! {
    todo!("0xf64214 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")
}

// 0xf64204 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E
// type: void __fastcall(int, _DWORD *) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(int, _DWORD *)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")]
pub fn stub_f64204() -> ! {
    todo!("0xf64204 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")
}

// 0xf641f4 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_
// type: int __fastcall(int, _Rb_tree_node_base *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _Rb_tree_node_base *, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")]
pub fn stub_f641f4() -> ! {
    todo!("0xf641f4 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")
}

// 0xf641e4 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_
// type: int __fastcall(int, _DWORD *, unsigned int *M_color, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _DWORD *, unsigned int *M_color, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")]
pub fn stub_f641e4() -> ! {
    todo!("0xf641e4 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")
}

// 0xf641d4 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")]
pub fn stub_f641d4() -> ! {
    todo!("0xf641d4 j___ZNSt8_Rb_treeIPKN3RBX10Reflection18PropertyDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")
}

// 0xf641b4 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E
// type: void __fastcall(int, _DWORD *) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(int, _DWORD *)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")]
pub fn stub_f641b4() -> ! {
    todo!("0xf641b4 j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE8_M_eraseEPSt13_Rb_tree_nodeISC_E")
}

// 0xf641a4 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_
// type: _Rb_tree_node_base *__fastcall(int, _Rb_tree_node_base *, unsigned int *M_right, int) — uses boost, now rbx_core::SharedPtr
// was: _Rb_tree_node_base *__fastcall(int, _Rb_tree_node_base *, unsigned int *M_right, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")]
pub fn stub_f641a4() -> ! {
    todo!("0xf641a4 j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueESt17_Rb_tree_iteratorISC_ERKSC_")
}

// 0xf64194 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_
// type: int __fastcall(int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")]
pub fn stub_f64194() -> ! {
    todo!("0xf64194 j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE16_M_insert_uniqueERKSC_")
}

// 0xf64184 — j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_
// type: _DWORD *__fastcall(int, int *, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: _DWORD *__fastcall(int, int *, int, int, struct _Unwind_Exception *lpuexcpt, void *, int, int, void *, int)
#[doc(alias = "j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")]
pub fn stub_f64184() -> ! {
    todo!("0xf64184 j___ZNSt8_Rb_treeIPKN3RBX10Reflection15EventDescriptorESt4pairIKS4_N5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEEESt10_Select1stISC_ESt4lessIS4_ESaISC_EE14_M_create_nodeERKSC_")
}

// 0xf64164 — j___ZNSt8_Rb_treeIN3RBX4Guid4DataESt4pairIKS2_St6vectorINS0_7Network12IdSerializer8WaitItemESaIS8_EEESt10_Select1stISB_ESt4lessIS2_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E
// type: void __fastcall(int, _DWORD *)
#[doc(alias = "j___ZNSt8_Rb_treeIN3RBX4Guid4DataESt4pairIKS2_St6vectorINS0_7Network12IdSerializer8WaitItemESaIS8_EEESt10_Select1stISB_ESt4lessIS2_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E")]
pub fn stub_f64164() -> ! {
    todo!("0xf64164 j___ZNSt8_Rb_treeIN3RBX4Guid4DataESt4pairIKS2_St6vectorINS0_7Network12IdSerializer8WaitItemESaIS8_EEESt10_Select1stISB_ESt4lessIS2_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E")
}

// 0xf64094 — j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EED2Ev
// type: int __fastcall(int, int, int, int, int, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, int, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt, int)
#[doc(alias = "j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EED2Ev")]
pub fn stub_f64094() -> ! {
    todo!("0xf64094 j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EED2Ev")
}

// 0xf64084 — j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EEC2ERKS7_
// type: int __fastcall(int, _DWORD *, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, _DWORD *, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, struct _Unwind_Exception *lpuexcpt)
#[doc(alias = "j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EEC2ERKS7_")]
pub fn stub_f64084() -> ! {
    todo!("0xf64084 j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EEC2ERKS7_")
}

// 0xf64074 — j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_reallocate_mapEmb
// type: int __fastcall(_DWORD, _DWORD, _DWORD) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(_DWORD, _DWORD, _DWORD)
#[doc(alias = "j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_reallocate_mapEmb")]
pub fn stub_f64074() -> ! {
    todo!("0xf64074 j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_reallocate_mapEmb")
}

// 0xf64064 — j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE16_M_push_back_auxERKS5_
// type: void __fastcall(_DWORD *, int *, int, int, int, int, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, int *, int, int, int, int, int, int, void *, int)
#[doc(alias = "j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE16_M_push_back_auxERKS5_")]
pub fn stub_f64064() -> ! {
    todo!("0xf64064 j___ZNSt5dequeIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE16_M_push_back_auxERKS5_")
}

// 0xf64034 — j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_
// type: int __fastcall(int, int, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")]
pub fn stub_f64034() -> ! {
    todo!("0xf64034 j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network31SharedStringProtectedDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")
}

// 0xf64024 — j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_
// type: _Rb_tree_node_base **__fastcall(int, int *, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: _Rb_tree_node_base **__fastcall(int, int *, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")]
pub fn stub_f64024() -> ! {
    todo!("0xf64024 j___ZNSt3mapIPKN3RBX10Reflection18PropertyDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")
}

// 0xf64014 — j___ZNSt3mapIPKN3RBX10Reflection15EventDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_
// type: int __fastcall(int, int, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, int, pthread_mutex_t *, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNSt3mapIPKN3RBX10Reflection15EventDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")]
pub fn stub_f64014() -> ! {
    todo!("0xf64014 j___ZNSt3mapIPKN3RBX10Reflection15EventDescriptorEN5boost10shared_ptrINS0_7Network22SharedStringDictionaryEEESt4lessIS4_ESaISt4pairIKS4_S9_EEEixERSD_")
}

// 0xf64004 — j___ZNSt11_Deque_baseIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_initialize_mapEm
// type: void __fastcall(_DWORD *, unsigned int, int, int, int, int, int, int, void *, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, unsigned int, int, int, int, int, int, int, void *, int)
#[doc(alias = "j___ZNSt11_Deque_baseIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_initialize_mapEm")]
pub fn stub_f64004() -> ! {
    todo!("0xf64004 j___ZNSt11_Deque_baseIN5boost10shared_ptrIN3RBX7Network6MarkerEEESaIS5_EE17_M_initialize_mapEm")
}

// 0xf63fb4 — j___ZNK5boost6detail8function13basic_vtable1IvPN3RBX9DataModelEE9assign_toINS_3_bi6bind_tIvPFvNS_10shared_ptrINS3_8InstanceEEEENS8_5list1INS8_5valueINSA_INS3_7Network10ReplicatorEEEEEEEEEEEbT_RNS1_15function_bufferENS1_16function_obj_tagE
// type: int __fastcall(int, int *, int *, int, pthread_mutex_t *, int, struct _Unwind_Exception *lpuexcpt, int, int, pthread_mutex_t *, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int *, int *, int, pthread_mutex_t *, int, struct _Unwind_Exception *lpuexcpt, int, int, pthread_mutex_t *, int, int, int, int)
#[doc(alias = "j___ZNK5boost6detail8function13basic_vtable1IvPN3RBX9DataModelEE9assign_toINS_3_bi6bind_tIvPFvNS_10shared_ptrINS3_8InstanceEEEENS8_5list1INS8_5valueINSA_INS3_7Network10ReplicatorEEEEEEEEEEEbT_RNS1_15function_bufferENS1_16function_obj_tagE")]
pub fn stub_f63fb4() -> ! {
    todo!("0xf63fb4 j___ZNK5boost6detail8function13basic_vtable1IvPN3RBX9DataModelEE9assign_toINS_3_bi6bind_tIvPFvNS_10shared_ptrINS3_8InstanceEEEENS8_5list1INS8_5valueINSA_INS3_7Network10ReplicatorEEEEEEEEEEEbT_RNS1_15function_bufferENS1_16function_obj_tagE")
}

// 0xf63fa4 — j___ZNK5boost4_mfi3mf2IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEENS_8functionIFvS7_EEEEclEPS4_S7_SA_
// type: void __fastcall(char **, int, int *, int *, int, pthread_mutex_t *, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(char **, int, int *, int *, int, pthread_mutex_t *, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf2IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEENS_8functionIFvS7_EEEEclEPS4_S7_SA_")]
pub fn stub_f63fa4() -> ! {
    todo!("0xf63fa4 j___ZNK5boost4_mfi3mf2IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEENS_8functionIFvS7_EEEEclEPS4_S7_SA_")
}

// 0xf63f94 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_
// type: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")]
pub fn stub_f63f94() -> ! {
    todo!("0xf63f94 j___ZNK5boost4_mfi3mf1IvN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")
}

// 0xf63f84 — j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator12JoinDataItemENS_10shared_ptrIKNS2_8InstanceEEEEclEPS5_S9_
// type: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(char **, int, int *, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator12JoinDataItemENS_10shared_ptrIKNS2_8InstanceEEEEclEPS5_S9_")]
pub fn stub_f63f84() -> ! {
    todo!("0xf63f84 j___ZNK5boost4_mfi3mf1IvN3RBX7Network10Replicator12JoinDataItemENS_10shared_ptrIKNS2_8InstanceEEEEclEPS5_S9_")
}

// 0xf63f74 — j___ZNK5boost4_mfi3mf1IbN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost4_mfi3mf1IbN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")]
pub fn stub_f63f74() -> ! {
    todo!("0xf63f74 j___ZNK5boost4_mfi3mf1IbN3RBX7Network10ReplicatorENS_10shared_ptrINS2_8InstanceEEEEclEPS4_S7_")
}

// 0xf63f64 — j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator7PingJobES8_EEvPKNS_10shared_ptrIT_EEPT0_
// type: void __fastcall(_DWORD *, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator7PingJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")]
pub fn stub_f63f64() -> ! {
    todo!("0xf63f64 j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator7PingJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")
}

// 0xf63f54 — j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator17ProcessPacketsJobES8_EEvPKNS_10shared_ptrIT_EEPT0_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator17ProcessPacketsJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")]
pub fn stub_f63f54() -> ! {
    todo!("0xf63f54 j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator17ProcessPacketsJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")
}

// 0xf63f44 — j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator14SendClusterJobES8_EEvPKNS_10shared_ptrIT_EEPT0_
// type: void __fastcall(_DWORD *, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(_DWORD *, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator14SendClusterJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")]
pub fn stub_f63f44() -> ! {
    todo!("0xf63f44 j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator14SendClusterJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")
}

// 0xf63f34 — j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator11SendDataJobES8_EEvPKNS_10shared_ptrIT_EEPT0_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator11SendDataJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")]
pub fn stub_f63f34() -> ! {
    todo!("0xf63f34 j___ZNK5boost23enable_shared_from_thisIN3RBX13TaskScheduler3JobEE22_internal_accept_ownerINS1_7Network10Replicator11SendDataJobES8_EEvPKNS_10shared_ptrIT_EEPT0_")
}

// 0xf63f14 — j___ZNK5boost23enable_shared_from_thisIN3RBX10Reflection13DescribedBaseEE22_internal_accept_ownerINS1_7Network6MarkerES7_EEvPKNS_10shared_ptrIT_EEPT0_
// type: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, pthread_mutex_t *, int, pthread_mutex_t *, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK5boost23enable_shared_from_thisIN3RBX10Reflection13DescribedBaseEE22_internal_accept_ownerINS1_7Network6MarkerES7_EEvPKNS_10shared_ptrIT_EEPT0_")]
pub fn stub_f63f14() -> ! {
    todo!("0xf63f14 j___ZNK5boost23enable_shared_from_thisIN3RBX10Reflection13DescribedBaseEE22_internal_accept_ownerINS1_7Network6MarkerES7_EEvPKNS_10shared_ptrIT_EEPT0_")
}

// 0xf63ec4 — j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10ReplicatorENS2_10shared_ptrIS0_EENS2_8functionIFvSA_EEEEENS3_5list3INS3_5valueIPS8_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_
// type: void __fastcall(int, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: void __fastcall(int, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10ReplicatorENS2_10shared_ptrIS0_EENS2_8functionIFvSA_EEEEENS3_5list3INS3_5valueIPS8_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_")]
pub fn stub_f63ec4() -> ! {
    todo!("0xf63ec4 j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIvNS2_4_mfi3mf2IvNS_7Network10ReplicatorENS2_10shared_ptrIS0_EENS2_8functionIFvSA_EEEEENS3_5list3INS3_5valueIPS8_EENS2_3argILi1EEENSG_ISD_EEEEEEEEvRKT_")
}

// 0xf63eb4 — j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIbNS2_4_mfi3mf1IbNS_7Network10ReplicatorENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS8_EENS2_3argILi1EEEEEEEEEvRKT_
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int) — uses boost, now rbx_core::SharedPtr
// was: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, int, int, int, int, int, int, int, int, int)
#[doc(alias = "j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIbNS2_4_mfi3mf1IbNS_7Network10ReplicatorENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS8_EENS2_3argILi1EEEEEEEEEvRKT_")]
pub fn stub_f63eb4() -> ! {
    todo!("0xf63eb4 j___ZNK3RBX8Instance13visitChildrenIN5boost3_bi6bind_tIbNS2_4_mfi3mf1IbNS_7Network10ReplicatorENS2_10shared_ptrIS0_EEEENS3_5list2INS3_5valueIPS8_EENS2_3argILi1EEEEEEEEEvRKT_")
}

// 0xf63e44 — j___ZNK3RBX5Voxel10SerializerINS_19MegaClusterInstanceEE18encodeFromPositionINS_7Network19ClusterUpdateBufferEN6RakNet9BitStreamEEEvPKS2_RN3G3D12Vector3int16ERKNS_13SpatialRegion2IdERKNS0_6RegionINS2_9CellChunkEEERNS_23FixedSizeCircularBufferIjLi8EEERT_PT0_
// type: unsigned int __fastcall(int, int, __int16 *, unsigned __int16 *, RBX::MegaClusterInstance::CellChunk **, int, RBX::Network::ClusterUpdateBuffer *, RakNet::BitStream *)
#[doc(alias = "j___ZNK3RBX5Voxel10SerializerINS_19MegaClusterInstanceEE18encodeFromPositionINS_7Network19ClusterUpdateBufferEN6RakNet9BitStreamEEEvPKS2_RN3G3D12Vector3int16ERKNS_13SpatialRegion2IdERKNS0_6RegionINS2_9CellChunkEEERNS_23FixedSizeCircularBufferIjLi8EEERT_PT0_")]
pub fn stub_f63e44() -> ! {
    todo!("0xf63e44 j___ZNK3RBX5Voxel10SerializerINS_19MegaClusterInstanceEE18encodeFromPositionINS_7Network19ClusterUpdateBufferEN6RakNet9BitStreamEEEvPKS2_RN3G3D12Vector3int16ERKNS_13SpatialRegion2IdERKNS0_6RegionINS2_9CellChunkEEERNS_23FixedSizeCircularBufferIjLi8EEERT_PT0_")
}
