//! platform — generated_plat_globaldedup_117 — 20 stubs EA-sorted asc, global-dedup vs /tmp/global_eas.txt (Ogre Compositor/Controller tail thunks for iOS GLES2 hosting)
//! Source: ida/export.json (85545 funcs) | filter: platform-namespace remainder (this batch 0xf66d84..0xf66eb4) | rbx_core::SharedPtr not boost

#![allow(non_snake_case, dead_code, unused_variables, unused_imports, clippy::all)]

use rbx_core::SharedPtr;

const _: () = {
    let _ = core::marker::PhantomData::<SharedPtr<u8>>;
};

// 0xf66d84 — j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_NS0_10TexturePtrEESt10_Select1stIS6_ENS1_14TextureDefLessENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS6_E
// demangled: std::_Rb_tree<Ogre::CompositorManager::TextureDef,std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,std::_Select1st<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>>,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>> *)
#[doc(alias = "std::_Rb_tree<Ogre::CompositorManager::TextureDef,std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,std::_Select1st<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>>,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_NS0_10TexturePtrEESt10_Select1stIS6_ENS1_14TextureDefLessENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS6_E")]
pub fn stub_0xf66d84() -> ! {
    todo!("0xf66d84 j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_NS0_10TexturePtrEESt10_Select1stIS6_ENS1_14TextureDefLessENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS6_E")
}

// 0xf66d94 — j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_PSt6vectorINS0_10TexturePtrENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ENS1_14TextureDefLessENS7_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E
// demangled: std::_Rb_tree<Ogre::CompositorManager::TextureDef,std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>> *)
#[doc(alias = "std::_Rb_tree<Ogre::CompositorManager::TextureDef,std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::CompositorManager::TextureDef const,std::vector<Ogre::TexturePtr,Ogre::STLAllocator<Ogre::TexturePtr,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_PSt6vectorINS0_10TexturePtrENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ENS1_14TextureDefLessENS7_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E")]
pub fn stub_0xf66d94() -> ! {
    todo!("0xf66d94 j___ZNSt8_Rb_treeIN4Ogre17CompositorManager10TextureDefESt4pairIKS2_PSt6vectorINS0_10TexturePtrENS0_12STLAllocatorIS6_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ENS1_14TextureDefLessENS7_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E")
}

// 0xf66da4 — j___ZNSt8_Rb_treeIPN4Ogre7TextureES2_St9_IdentityIS2_ESt4lessIS2_ENS0_12STLAllocatorIS2_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS2_
// demangled: std::_Rb_tree<Ogre::Texture *,Ogre::Texture *,std::_Identity<Ogre::Texture *>,std::less<Ogre::Texture *>,Ogre::STLAllocator<Ogre::Texture *,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(Ogre::Texture * const&)
// type: int __fastcall(char *)
#[doc(alias = "std::_Rb_tree<Ogre::Texture *,Ogre::Texture *,std::_Identity<Ogre::Texture *>,std::less<Ogre::Texture *>,Ogre::STLAllocator<Ogre::Texture *,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(Ogre::Texture * const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeIPN4Ogre7TextureES2_St9_IdentityIS2_ESt4lessIS2_ENS0_12STLAllocatorIS2_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS2_")]
pub fn stub_0xf66da4() -> ! {
    todo!("0xf66da4 j___ZNSt8_Rb_treeIPN4Ogre7TextureES2_St9_IdentityIS2_ESt4lessIS2_ENS0_12STLAllocatorIS2_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS2_")
}

// 0xf66db4 — j___ZNSt8_Rb_treeIPN4Ogre8ViewportESt4pairIKS2_PNS0_15CompositorChainEESt10_Select1stIS7_ESt4lessIS2_ENS0_12STLAllocatorIS7_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS7_E
// demangled: std::_Rb_tree<Ogre::Viewport *,std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>,std::_Select1st<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>>,std::less<Ogre::Viewport *>,Ogre::STLAllocator<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>> *)
#[doc(alias = "std::_Rb_tree<Ogre::Viewport *,std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>,std::_Select1st<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>>,std::less<Ogre::Viewport *>,Ogre::STLAllocator<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<Ogre::Viewport * const,Ogre::CompositorChain *>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeIPN4Ogre8ViewportESt4pairIKS2_PNS0_15CompositorChainEESt10_Select1stIS7_ESt4lessIS2_ENS0_12STLAllocatorIS7_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS7_E")]
pub fn stub_0xf66db4() -> ! {
    todo!("0xf66db4 j___ZNSt8_Rb_treeIPN4Ogre8ViewportESt4pairIKS2_PNS0_15CompositorChainEESt10_Select1stIS7_ESt4lessIS2_ENS0_12STLAllocatorIS7_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS7_E")
}

// 0xf66dc4 — j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre15CompositorLogicEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,Ogre::CompositorLogic *>,std::_Select1st<std::pair<std::string const,Ogre::CompositorLogic *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,Ogre::CompositorLogic *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,Ogre::CompositorLogic *>> *)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,Ogre::CompositorLogic *>,std::_Select1st<std::pair<std::string const,Ogre::CompositorLogic *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,Ogre::CompositorLogic *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,Ogre::CompositorLogic *>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre15CompositorLogicEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E")]
pub fn stub_0xf66dc4() -> ! {
    todo!("0xf66dc4 j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre15CompositorLogicEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E")
}

// 0xf66dd4 — j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre21CustomCompositionPassEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,Ogre::CustomCompositionPass *>,std::_Select1st<std::pair<std::string const,Ogre::CustomCompositionPass *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,Ogre::CustomCompositionPass *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,Ogre::CustomCompositionPass *>> *)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,Ogre::CustomCompositionPass *>,std::_Select1st<std::pair<std::string const,Ogre::CustomCompositionPass *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,Ogre::CustomCompositionPass *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,Ogre::CustomCompositionPass *>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre21CustomCompositionPassEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E")]
pub fn stub_0xf66dd4() -> ! {
    todo!("0xf66dd4 j___ZNSt8_Rb_treeISsSt4pairIKSsPN4Ogre21CustomCompositionPassEESt10_Select1stIS5_ESt4lessISsENS2_12STLAllocatorIS5_NS2_22CategorisedAllocPolicyILNS2_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS5_E")
}

// 0xf66de4 — j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeISH_E
// demangled: std::_Rb_tree<std::pair<std::string,std::string>,std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::_Select1st<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>,std::less<std::pair<std::string,std::string>>,std::allocator<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>>::_M_destroy_node(std::_Rb_tree_node<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>> *)
#[doc(alias = "std::_Rb_tree<std::pair<std::string,std::string>,std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::_Select1st<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>,std::less<std::pair<std::string,std::string>>,std::allocator<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>>::_M_destroy_node(std::_Rb_tree_node<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeISH_E")]
pub fn stub_0xf66de4() -> ! {
    todo!("0xf66de4 j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeISH_E")
}

// 0xf66df4 — j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE8_M_eraseEPSt13_Rb_tree_nodeISH_E
// demangled: std::_Rb_tree<std::pair<std::string,std::string>,std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::_Select1st<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>,std::less<std::pair<std::string,std::string>>,std::allocator<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>>::_M_erase(std::_Rb_tree_node<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>> *)
#[doc(alias = "std::_Rb_tree<std::pair<std::string,std::string>,std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::_Select1st<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>,std::less<std::pair<std::string,std::string>>,std::allocator<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>>>::_M_erase(std::_Rb_tree_node<std::pair<std::pair<std::string,std::string> const,std::map<Ogre::CompositorManager::TextureDef,Ogre::TexturePtr,Ogre::CompositorManager::TextureDefLess,Ogre::STLAllocator<std::pair<Ogre::CompositorManager::TextureDef const,Ogre::TexturePtr>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE8_M_eraseEPSt13_Rb_tree_nodeISH_E")]
pub fn stub_0xf66df4() -> ! {
    todo!("0xf66df4 j___ZNSt8_Rb_treeISt4pairISsSsES0_IKS1_St3mapIN4Ogre17CompositorManager10TextureDefENS4_10TexturePtrENS5_14TextureDefLessENS4_12STLAllocatorIS0_IKS6_S7_ENS4_22CategorisedAllocPolicyILNS4_14MemoryCategoryE0EEEEEEESt10_Select1stISH_ESt4lessIS1_ESaISH_EE8_M_eraseEPSt13_Rb_tree_nodeISH_E")
}

// 0xf66e04 — j___ZNKSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)const
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)const")]
#[doc(alias = "j___ZNKSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_")]
pub fn stub_0xf66e04() -> ! {
    todo!("0xf66e04 j___ZNKSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_")
}

// 0xf66e14 — j___ZNSt3mapISsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorISt4pairIKSsSsENS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEES2_NS4_IS5_IS6_SD_ESA_EEEixERS6_
// demangled: std::map<std::string,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::operator[](std::string const&)
#[doc(alias = "std::map<std::string,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::operator[](std::string const&)")]
#[doc(alias = "j___ZNSt3mapISsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorISt4pairIKSsSsENS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEES2_NS4_IS5_IS6_SD_ESA_EEEixERS6_")]
pub fn stub_0xf66e14() -> ! {
    todo!("0xf66e14 j___ZNSt3mapISsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorISt4pairIKSsSsENS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEES2_NS4_IS5_IS6_SD_ESA_EEEixERS6_")
}

// 0xf66e24 — j___ZNSt6vectorISsN4Ogre12STLAllocatorISsNS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPSsS6_EERKSs
// demangled: std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string *,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::string const&)
// type: int __fastcall(int, int)
#[doc(alias = "std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string *,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>>,std::string const&)")]
#[doc(alias = "j___ZNSt6vectorISsN4Ogre12STLAllocatorISsNS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPSsS6_EERKSs")]
pub fn stub_0xf66e24() -> ! {
    todo!("0xf66e24 j___ZNSt6vectorISsN4Ogre12STLAllocatorISsNS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPSsS6_EERKSs")
}

// 0xf66e34 — j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueERKSE_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)
// type: int __fastcall(int, int, struct _Unwind_Exception *lpuexcpt)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueERKSE_")]
pub fn stub_0xf66e34() -> ! {
    todo!("0xf66e34 j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueERKSE_")
}

// 0xf66e44 — j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueESt17_Rb_tree_iteratorISE_ERKSE_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::_Rb_tree_iterator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)
// type: int __fastcall(int, int, struct _Unwind_Exception *lpuexcpt)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::_Rb_tree_iterator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueESt17_Rb_tree_iteratorISE_ERKSE_")]
pub fn stub_0xf66e44() -> ! {
    todo!("0xf66e44 j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE16_M_insert_uniqueESt17_Rb_tree_iteratorISE_ERKSE_")
}

// 0xf66e54 — j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_")]
pub fn stub_0xf66e54() -> ! {
    todo!("0xf66e54 j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE4findERS1_")
}

// 0xf66e64 — j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>> *)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>> *)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E")]
pub fn stub_0xf66e64() -> ! {
    todo!("0xf66e64 j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE8_M_eraseEPSt13_Rb_tree_nodeISE_E")
}

// 0xf66e74 — j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKSE_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert(std::_Rb_tree_node_base *,std::_Rb_tree_node_base *,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)
// type: int __fastcall(int, int, int, int, struct _Unwind_Exception *lpuexcpt, Ogre::NedPoolingImpl *, int, int, void *, int)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,std::_Select1st<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert(std::_Rb_tree_node_base *,std::_Rb_tree_node_base *,std::pair<std::string const,std::multimap<std::string,std::string,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> *> const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKSE_")]
pub fn stub_0xf66e74() -> ! {
    todo!("0xf66e74 j___ZNSt8_Rb_treeISsSt4pairIKSsPSt8multimapISsSsSt4lessISsEN4Ogre12STLAllocatorIS0_IS1_SsENS5_22CategorisedAllocPolicyILNS5_14MemoryCategoryE0EEEEEEESt10_Select1stISE_ES4_NS6_ISE_SA_EEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKSE_")
}

// 0xf66e84 — j___ZNSt8_Rb_treeISsSt4pairIKSsSsESt10_Select1stIS2_ESt4lessISsEN4Ogre12STLAllocatorIS2_NS7_22CategorisedAllocPolicyILNS7_14MemoryCategoryE0EEEEEE4findERS1_
// demangled: std::_Rb_tree<std::string,std::pair<std::string const,std::string>,std::_Select1st<std::pair<std::string const,std::string>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,std::string>,std::_Select1st<std::pair<std::string const,std::string>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,std::string>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::find(std::string const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeISsSt4pairIKSsSsESt10_Select1stIS2_ESt4lessISsEN4Ogre12STLAllocatorIS2_NS7_22CategorisedAllocPolicyILNS7_14MemoryCategoryE0EEEEEE4findERS1_")]
pub fn stub_0xf66e84() -> ! {
    todo!("0xf66e84 j___ZNSt8_Rb_treeISsSt4pairIKSsSsESt10_Select1stIS2_ESt4lessISsEN4Ogre12STLAllocatorIS2_NS7_22CategorisedAllocPolicyILNS7_14MemoryCategoryE0EEEEEE4findERS1_")
}

// 0xf66e94 — j___ZN4Ogre10ControllerIfEC2ERKNS_9SharedPtrINS_15ControllerValueIfEEEES7_RKNS2_INS_18ControllerFunctionIfEEEE
// demangled: Ogre::Controller<float>::Controller(Ogre::SharedPtr<Ogre::ControllerValue<float>> const&,Ogre::SharedPtr<Ogre::ControllerValue<float>> const&,Ogre::SharedPtr<Ogre::ControllerFunction<float>> const&)
#[doc(alias = "Ogre::Controller<float>::Controller(Ogre::SharedPtr<Ogre::ControllerValue<float>> const&,Ogre::SharedPtr<Ogre::ControllerValue<float>> const&,Ogre::SharedPtr<Ogre::ControllerFunction<float>> const&)")]
#[doc(alias = "j___ZN4Ogre10ControllerIfEC2ERKNS_9SharedPtrINS_15ControllerValueIfEEEES7_RKNS2_INS_18ControllerFunctionIfEEEE")]
pub fn stub_0xf66e94() -> ! {
    todo!("0xf66e94 j___ZN4Ogre10ControllerIfEC2ERKNS_9SharedPtrINS_15ControllerValueIfEEEES7_RKNS2_INS_18ControllerFunctionIfEEEE")
}

// 0xf66ea4 — j___ZN4Ogre10ControllerIfED2Ev
// demangled: Ogre::Controller<float>::~Controller()
#[doc(alias = "Ogre::Controller<float>::~Controller()")]
#[doc(alias = "j___ZN4Ogre10ControllerIfED2Ev")]
pub fn stub_0xf66ea4() -> ! {
    todo!("0xf66ea4 j___ZN4Ogre10ControllerIfED2Ev")
}

// 0xf66eb4 — j___ZNSt8_Rb_treeIPN4Ogre10ControllerIfEES3_St9_IdentityIS3_ESt4lessIS3_ENS0_12STLAllocatorIS3_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS3_
// demangled: std::_Rb_tree<Ogre::Controller<float> *,Ogre::Controller<float> *,std::_Identity<Ogre::Controller<float> *>,std::less<Ogre::Controller<float> *>,Ogre::STLAllocator<Ogre::Controller<float> *,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(Ogre::Controller<float> * const&)
// type: int __fastcall(char *)
#[doc(alias = "std::_Rb_tree<Ogre::Controller<float> *,Ogre::Controller<float> *,std::_Identity<Ogre::Controller<float> *>,std::less<Ogre::Controller<float> *>,Ogre::STLAllocator<Ogre::Controller<float> *,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(Ogre::Controller<float> * const&)")]
#[doc(alias = "j___ZNSt8_Rb_treeIPN4Ogre10ControllerIfEES3_St9_IdentityIS3_ESt4lessIS3_ENS0_12STLAllocatorIS3_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS3_")]
pub fn stub_0xf66eb4() -> ! {
    todo!("0xf66eb4 j___ZNSt8_Rb_treeIPN4Ogre10ControllerIfEES3_St9_IdentityIS3_ESt4lessIS3_ENS0_12STLAllocatorIS3_NS0_22CategorisedAllocPolicyILNS0_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS3_")
}
