// Auto-generated skeletons for rbx-script — Script/Lua/Yield/LuaBridge/ProtectedString gap filler
// Filter: Script|Lua|LuaBridge|Yield|ProtectedString (filtered 4921, 866 remaining before batch — EA-sorted asc distinct not yet in any crate)
// Source: ida/export.json (85545 funcs, base 0x4000)
// Batch: +120 stubs | range 0x824b14..0xd01bc0 | EA-sorted asc distinct not yet in any crate (remaining 30593->30473, rbx_core::SharedPtr not boost)
// SharedPtr = rbx_core::SharedPtr (Arc), not boost::shared_ptr;  and  stripped from alias

#![allow(non_snake_case, dead_code, unused_variables, unused_imports, clippy::all)]

use rbx_core::SharedPtr;

const _: () = {
    let _ = core::marker::PhantomData::<SharedPtr<u8>>;
};

// 0x824b14 — __Z18luaL_loadprotectedP9lua_StateRKN3RBX15ProtectedStringEPKc — luaL_loadprotected(lua_State *,RBX::ProtectedString const&,char const*)
#[doc(alias = "luaL_loadprotected(lua_State *,RBX::ProtectedString const&,char const*)")]
#[doc(alias = "__Z18luaL_loadprotectedP9lua_StateRKN3RBX15ProtectedStringEPKc")]
pub fn stub_0x824b14() -> ! {
    todo!("0x824b14 __Z18luaL_loadprotectedP9lua_StateRKN3RBX15ProtectedStringEPKc")
}

// 0x9e6880 — __ZN3RBX10Reflection9DescribedINS_6ScriptELZNS_7sScriptEENS_14FactoryProductIS2_NS_10BaseScriptELZNS_7sScriptEENS_8InstanceEEELNS0_15ClassDescriptor13FunctionalityE27ELNS_8Security11PermissionsE0EE15classDescriptorEv — __ZN3RBX10Reflection9DescribedINS_6ScriptELZNS_7sScriptEENS_14FactoryProductIS2_NS_10BaseScriptELZNS_7sScriptEENS_8InstanceEEELNS0_15ClassDescriptor13FunctionalityE27ELNS_8Security11PermissionsE0EE15classDescriptorEv
#[doc(alias = "__ZN3RBX10Reflection9DescribedINS_6ScriptELZNS_7sScriptEENS_14FactoryProductIS2_NS_10BaseScriptELZNS_7sScriptEENS_8InstanceEEELNS0_15ClassDescriptor13FunctionalityE27ELNS_8Security11PermissionsE0EE15classDescriptorEv")]
pub fn stub_0x9e6880() -> ! {
    todo!("0x9e6880 __ZN3RBX10Reflection9DescribedINS_6ScriptELZNS_7sScriptEENS_14FactoryProductIS2_NS_10BaseScriptELZNS_7sScriptEENS_8InstanceEEELNS0_15ClassDescriptor13FunctionalityE27ELNS_8Security11PermissionsE0EE15classDescriptorEv")
}

// 0xa23780 — __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorD2Ev — __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorD2Ev
#[doc(alias = "__ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorD2Ev")]
pub fn stub_0xa23780() -> ! {
    todo!("0xa23780 __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorD2Ev")
}

// 0xa23af0 — __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorC2Ev — __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorC2Ev
#[doc(alias = "__ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorC2Ev")]
pub fn stub_0xa23af0() -> ! {
    todo!("0xa23af0 __ZN3RBX14FactoryProductINS_11LocalScriptENS_6ScriptELZNS_12sLocalScriptEENS_8InstanceEE7CreatorC2Ev")
}

// 0xa85188 — __ZN3RBX7Network6Player31removeCharacterAppearanceScriptEv — RBX::Network::Player::removeCharacterAppearanceScript(void)
#[doc(alias = "RBX::Network::Player::removeCharacterAppearanceScript(void)")]
#[doc(alias = "__ZN3RBX7Network6Player31removeCharacterAppearanceScriptEv")]
pub fn stub_0xa85188() -> ! {
    todo!("0xa85188 __ZN3RBX7Network6Player31removeCharacterAppearanceScriptEv")
}

// 0xbb5020 — __ZN4Ogre20ShaderScriptListenerD1Ev — Ogre::ShaderScriptListener::~ShaderScriptListener()
#[doc(alias = "Ogre::ShaderScriptListener::~ShaderScriptListener()")]
#[doc(alias = "__ZN4Ogre20ShaderScriptListenerD1Ev")]
pub fn stub_0xbb5020() -> ! {
    todo!("0xbb5020 __ZN4Ogre20ShaderScriptListenerD1Ev")
}

// 0xbb507c — __ZN4Ogre20ShaderScriptListenerD0Ev — Ogre::ShaderScriptListener::~ShaderScriptListener()
#[doc(alias = "Ogre::ShaderScriptListener::~ShaderScriptListener()")]
#[doc(alias = "__ZN4Ogre20ShaderScriptListenerD0Ev")]
pub fn stub_0xbb507c() -> ! {
    todo!("0xbb507c __ZN4Ogre20ShaderScriptListenerD0Ev")
}

// 0xbb50dc — __ZN4Ogre20ShaderScriptListener11handleEventEPNS_14ScriptCompilerEPNS_19ScriptCompilerEventEPv — Ogre::ShaderScriptListener::handleEvent(Ogre::ScriptCompiler *,Ogre::ScriptCompilerEvent *,void *)
#[doc(alias = "Ogre::ShaderScriptListener::handleEvent(Ogre::ScriptCompiler *,Ogre::ScriptCompilerEvent *,void *)")]
#[doc(alias = "__ZN4Ogre20ShaderScriptListener11handleEventEPNS_14ScriptCompilerEPNS_19ScriptCompilerEventEPv")]
pub fn stub_0xbb50dc() -> ! {
    todo!("0xbb50dc __ZN4Ogre20ShaderScriptListener11handleEventEPNS_14ScriptCompilerEPNS_19ScriptCompilerEventEPv")
}

// 0xbb5440 — __ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE — Ogre::ShaderScriptListener::getAutogeneratedShaderPath(Ogre::CreateHighLevelGpuProgramScriptCompilerEvent const&)
#[doc(alias = "Ogre::ShaderScriptListener::getAutogeneratedShaderPath(Ogre::CreateHighLevelGpuProgramScriptCompilerEvent const&)")]
#[doc(alias = "__ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE")]
pub fn stub_0xbb5440() -> ! {
    todo!("0xbb5440 __ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKNS_44CreateHighLevelGpuProgramScriptCompilerEventE")
}

// 0xbb569c — __ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_ — Ogre::ShaderScriptListener::getAutogeneratedShaderPath(std::string const&,std::string const&,std::string const&)
#[doc(alias = "Ogre::ShaderScriptListener::getAutogeneratedShaderPath(std::string const&,std::string const&,std::string const&)")]
#[doc(alias = "__ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_")]
pub fn stub_0xbb569c() -> ! {
    todo!("0xbb569c __ZN4Ogre20ShaderScriptListener26getAutogeneratedShaderPathERKSsS2_S2_")
}

// 0xc75db0 — __ZN4Ogre17CompositorManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs — Ogre::CompositorManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)
#[doc(alias = "Ogre::CompositorManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)")]
#[doc(alias = "__ZN4Ogre17CompositorManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")]
pub fn stub_0xc75db0() -> ! {
    todo!("0xc75db0 __ZN4Ogre17CompositorManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")
}

// 0xc94c78 — __ZN4Ogre11FontManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs — Ogre::FontManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)
#[doc(alias = "Ogre::FontManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)")]
#[doc(alias = "__ZN4Ogre11FontManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")]
pub fn stub_0xc94c78() -> ! {
    todo!("0xc94c78 __ZN4Ogre11FontManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")
}

// 0xce23b4 — __ZN4Ogre15MaterialManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs — Ogre::MaterialManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)
#[doc(alias = "Ogre::MaterialManager::parseScript(Ogre::SharedPtr<Ogre::DataStream> &,std::string const&)")]
#[doc(alias = "__ZN4Ogre15MaterialManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")]
pub fn stub_0xce23b4() -> ! {
    todo!("0xce23b4 __ZN4Ogre15MaterialManager11parseScriptERNS_9SharedPtrINS_10DataStreamEEERKSs")
}

// 0xce39f4 — __ZN4Ogre13logParseErrorERKSsRKNS_21MaterialScriptContextE — Ogre::logParseError(std::string const&,Ogre::MaterialScriptContext const&)
#[doc(alias = "Ogre::logParseError(std::string const&,Ogre::MaterialScriptContext const&)")]
#[doc(alias = "__ZN4Ogre13logParseErrorERKSsRKNS_21MaterialScriptContextE")]
pub fn stub_0xce39f4() -> ! {
    todo!("0xce39f4 __ZN4Ogre13logParseErrorERKSsRKNS_21MaterialScriptContextE")
}

// 0xce4950 — __ZN4Ogre12parseAmbientERSsRNS_21MaterialScriptContextE — Ogre::parseAmbient(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAmbient(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre12parseAmbientERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce4950() -> ! {
    todo!("0xce4950 __ZN4Ogre12parseAmbientERSsRNS_21MaterialScriptContextE")
}

// 0xce4da8 — __ZN4Ogre12parseDiffuseERSsRNS_21MaterialScriptContextE — Ogre::parseDiffuse(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDiffuse(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre12parseDiffuseERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce4da8() -> ! {
    todo!("0xce4da8 __ZN4Ogre12parseDiffuseERSsRNS_21MaterialScriptContextE")
}

// 0xce5200 — __ZN4Ogre13parseSpecularERSsRNS_21MaterialScriptContextE — Ogre::parseSpecular(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseSpecular(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseSpecularERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce5200() -> ! {
    todo!("0xce5200 __ZN4Ogre13parseSpecularERSsRNS_21MaterialScriptContextE")
}

// 0xce56b0 — __ZN4Ogre13parseEmissiveERSsRNS_21MaterialScriptContextE — Ogre::parseEmissive(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseEmissive(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseEmissiveERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce56b0() -> ! {
    todo!("0xce56b0 __ZN4Ogre13parseEmissiveERSsRNS_21MaterialScriptContextE")
}

// 0xce5dd0 — __ZN4Ogre15parseSceneBlendERSsRNS_21MaterialScriptContextE — Ogre::parseSceneBlend(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseSceneBlend(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseSceneBlendERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce5dd0() -> ! {
    todo!("0xce5dd0 __ZN4Ogre15parseSceneBlendERSsRNS_21MaterialScriptContextE")
}

// 0xce64d0 — __ZN4Ogre23parseSeparateSceneBlendERSsRNS_21MaterialScriptContextE — Ogre::parseSeparateSceneBlend(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseSeparateSceneBlend(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre23parseSeparateSceneBlendERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce64d0() -> ! {
    todo!("0xce64d0 __ZN4Ogre23parseSeparateSceneBlendERSsRNS_21MaterialScriptContextE")
}

// 0xce7104 — __ZN4Ogre15parseDepthCheckERSsRNS_21MaterialScriptContextE — Ogre::parseDepthCheck(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDepthCheck(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseDepthCheckERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7104() -> ! {
    todo!("0xce7104 __ZN4Ogre15parseDepthCheckERSsRNS_21MaterialScriptContextE")
}

// 0xce7288 — __ZN4Ogre15parseDepthWriteERSsRNS_21MaterialScriptContextE — Ogre::parseDepthWrite(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDepthWrite(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseDepthWriteERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7288() -> ! {
    todo!("0xce7288 __ZN4Ogre15parseDepthWriteERSsRNS_21MaterialScriptContextE")
}

// 0xce740c — __ZN4Ogre17parseLightScissorERSsRNS_21MaterialScriptContextE — Ogre::parseLightScissor(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLightScissor(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseLightScissorERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce740c() -> ! {
    todo!("0xce740c __ZN4Ogre17parseLightScissorERSsRNS_21MaterialScriptContextE")
}

// 0xce7588 — __ZN4Ogre14parseLightClipERSsRNS_21MaterialScriptContextE — Ogre::parseLightClip(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLightClip(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseLightClipERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7588() -> ! {
    todo!("0xce7588 __ZN4Ogre14parseLightClipERSsRNS_21MaterialScriptContextE")
}

// 0xce7704 — __ZN4Ogre14parseDepthFuncERSsRNS_21MaterialScriptContextE — Ogre::parseDepthFunc(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDepthFunc(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseDepthFuncERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7704() -> ! {
    todo!("0xce7704 __ZN4Ogre14parseDepthFuncERSsRNS_21MaterialScriptContextE")
}

// 0xce7884 — __ZN4Ogre21parseNormaliseNormalsERSsRNS_21MaterialScriptContextE — Ogre::parseNormaliseNormals(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseNormaliseNormals(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre21parseNormaliseNormalsERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7884() -> ! {
    todo!("0xce7884 __ZN4Ogre21parseNormaliseNormalsERSsRNS_21MaterialScriptContextE")
}

// 0xce7a00 — __ZN4Ogre16parseColourWriteERSsRNS_21MaterialScriptContextE — Ogre::parseColourWrite(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseColourWrite(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseColourWriteERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7a00() -> ! {
    todo!("0xce7a00 __ZN4Ogre16parseColourWriteERSsRNS_21MaterialScriptContextE")
}

// 0xce7b84 — __ZN4Ogre17parseCullHardwareERSsRNS_21MaterialScriptContextE — Ogre::parseCullHardware(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseCullHardware(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseCullHardwareERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7b84() -> ! {
    todo!("0xce7b84 __ZN4Ogre17parseCullHardwareERSsRNS_21MaterialScriptContextE")
}

// 0xce7d2c — __ZN4Ogre17parseCullSoftwareERSsRNS_21MaterialScriptContextE — Ogre::parseCullSoftware(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseCullSoftware(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseCullSoftwareERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7d2c() -> ! {
    todo!("0xce7d2c __ZN4Ogre17parseCullSoftwareERSsRNS_21MaterialScriptContextE")
}

// 0xce7ed4 — __ZN4Ogre13parseLightingERSsRNS_21MaterialScriptContextE — Ogre::parseLighting(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLighting(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseLightingERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce7ed4() -> ! {
    todo!("0xce7ed4 __ZN4Ogre13parseLightingERSsRNS_21MaterialScriptContextE")
}

// 0xce8058 — __ZN4Ogre14parseMaxLightsERSsRNS_21MaterialScriptContextE — Ogre::parseMaxLights(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseMaxLights(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseMaxLightsERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8058() -> ! {
    todo!("0xce8058 __ZN4Ogre14parseMaxLightsERSsRNS_21MaterialScriptContextE")
}

// 0xce8070 — __ZN4Ogre15parseStartLightERSsRNS_21MaterialScriptContextE — Ogre::parseStartLight(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseStartLight(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseStartLightERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8070() -> ! {
    todo!("0xce8070 __ZN4Ogre15parseStartLightERSsRNS_21MaterialScriptContextE")
}

// 0xce8088 — __ZN4Ogre24parseIterationLightTypesERSsRNS_21MaterialScriptContextE — Ogre::parseIterationLightTypes(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseIterationLightTypes(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre24parseIterationLightTypesERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8088() -> ! {
    todo!("0xce8088 __ZN4Ogre24parseIterationLightTypesERSsRNS_21MaterialScriptContextE")
}

// 0xce8234 — __ZN4Ogre14parseIterationERSsRNS_21MaterialScriptContextE — Ogre::parseIteration(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseIteration(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseIterationERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8234() -> ! {
    todo!("0xce8234 __ZN4Ogre14parseIterationERSsRNS_21MaterialScriptContextE")
}

// 0xce8868 — __ZN4Ogre14parsePointSizeERSsRNS_21MaterialScriptContextE — Ogre::parsePointSize(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePointSize(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parsePointSizeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8868() -> ! {
    todo!("0xce8868 __ZN4Ogre14parsePointSizeERSsRNS_21MaterialScriptContextE")
}

// 0xce8880 — __ZN4Ogre17parsePointSpritesERSsRNS_21MaterialScriptContextE — Ogre::parsePointSprites(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePointSprites(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parsePointSpritesERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8880() -> ! {
    todo!("0xce8880 __ZN4Ogre17parsePointSpritesERSsRNS_21MaterialScriptContextE")
}

// 0xce89fc — __ZN4Ogre21parsePointAttenuationERSsRNS_21MaterialScriptContextE — Ogre::parsePointAttenuation(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePointAttenuation(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre21parsePointAttenuationERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce89fc() -> ! {
    todo!("0xce89fc __ZN4Ogre21parsePointAttenuationERSsRNS_21MaterialScriptContextE")
}

// 0xce8da4 — __ZN4Ogre17parsePointSizeMinERSsRNS_21MaterialScriptContextE — Ogre::parsePointSizeMin(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePointSizeMin(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parsePointSizeMinERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8da4() -> ! {
    todo!("0xce8da4 __ZN4Ogre17parsePointSizeMinERSsRNS_21MaterialScriptContextE")
}

// 0xce8dbc — __ZN4Ogre17parsePointSizeMaxERSsRNS_21MaterialScriptContextE — Ogre::parsePointSizeMax(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePointSizeMax(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parsePointSizeMaxERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8dbc() -> ! {
    todo!("0xce8dbc __ZN4Ogre17parsePointSizeMaxERSsRNS_21MaterialScriptContextE")
}

// 0xce8dd4 — __ZN4Ogre12parseFoggingERSsRNS_21MaterialScriptContextE — Ogre::parseFogging(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseFogging(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre12parseFoggingERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce8dd4() -> ! {
    todo!("0xce8dd4 __ZN4Ogre12parseFoggingERSsRNS_21MaterialScriptContextE")
}

// 0xce931c — __ZN4Ogre12parseShadingERSsRNS_21MaterialScriptContextE — Ogre::parseShading(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShading(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre12parseShadingERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce931c() -> ! {
    todo!("0xce931c __ZN4Ogre12parseShadingERSsRNS_21MaterialScriptContextE")
}

// 0xce94c4 — __ZN4Ogre16parsePolygonModeERSsRNS_21MaterialScriptContextE — Ogre::parsePolygonMode(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePolygonMode(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parsePolygonModeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce94c4() -> ! {
    todo!("0xce94c4 __ZN4Ogre16parsePolygonModeERSsRNS_21MaterialScriptContextE")
}

// 0xce966c — __ZN4Ogre28parsePolygonModeOverrideableERSsRNS_21MaterialScriptContextE — Ogre::parsePolygonModeOverrideable(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePolygonModeOverrideable(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre28parsePolygonModeOverrideableERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce966c() -> ! {
    todo!("0xce966c __ZN4Ogre28parsePolygonModeOverrideableERSsRNS_21MaterialScriptContextE")
}

// 0xce9690 — __ZN4Ogre14parseFilteringERSsRNS_21MaterialScriptContextE — Ogre::parseFiltering(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseFiltering(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseFilteringERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce9690() -> ! {
    todo!("0xce9690 __ZN4Ogre14parseFilteringERSsRNS_21MaterialScriptContextE")
}

// 0xce9c18 — __ZN4Ogre12parseTextureERSsRNS_21MaterialScriptContextE — Ogre::parseTexture(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTexture(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre12parseTextureERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xce9c18() -> ! {
    todo!("0xce9c18 __ZN4Ogre12parseTextureERSsRNS_21MaterialScriptContextE")
}

// 0xcea2e4 — __ZN4Ogre16parseBindingTypeERSsRNS_21MaterialScriptContextE — Ogre::parseBindingType(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseBindingType(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseBindingTypeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcea2e4() -> ! {
    todo!("0xcea2e4 __ZN4Ogre16parseBindingTypeERSsRNS_21MaterialScriptContextE")
}

// 0xcea568 — __ZN4Ogre16parseAnimTextureERSsRNS_21MaterialScriptContextE — Ogre::parseAnimTexture(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAnimTexture(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseAnimTextureERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcea568() -> ! {
    todo!("0xcea568 __ZN4Ogre16parseAnimTextureERSsRNS_21MaterialScriptContextE")
}

// 0xcea8c8 — __ZN4Ogre17parseCubicTextureERSsRNS_21MaterialScriptContextE — Ogre::parseCubicTexture(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseCubicTexture(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseCubicTextureERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcea8c8() -> ! {
    todo!("0xcea8c8 __ZN4Ogre17parseCubicTextureERSsRNS_21MaterialScriptContextE")
}

// 0xceaca4 — __ZN4Ogre13parseTexCoordERSsRNS_21MaterialScriptContextE — Ogre::parseTexCoord(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTexCoord(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseTexCoordERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceaca4() -> ! {
    todo!("0xceaca4 __ZN4Ogre13parseTexCoordERSsRNS_21MaterialScriptContextE")
}

// 0xceacbc — __ZN4Ogre18convTexAddressModeERKSsRNS_21MaterialScriptContextE — Ogre::convTexAddressMode(std::string const&,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::convTexAddressMode(std::string const&,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18convTexAddressModeERKSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceacbc() -> ! {
    todo!("0xceacbc __ZN4Ogre18convTexAddressModeERKSsRNS_21MaterialScriptContextE")
}

// 0xceae54 — __ZN4Ogre19parseTexAddressModeERSsRNS_21MaterialScriptContextE — Ogre::parseTexAddressMode(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTexAddressMode(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre19parseTexAddressModeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceae54() -> ! {
    todo!("0xceae54 __ZN4Ogre19parseTexAddressModeERSsRNS_21MaterialScriptContextE")
}

// 0xceb1a0 — __ZN4Ogre20parseTexBorderColourERSsRNS_21MaterialScriptContextE — Ogre::parseTexBorderColour(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTexBorderColour(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre20parseTexBorderColourERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceb1a0() -> ! {
    todo!("0xceb1a0 __ZN4Ogre20parseTexBorderColourERSsRNS_21MaterialScriptContextE")
}

// 0xceb4fc — __ZN4Ogre13parseColourOpERSsRNS_21MaterialScriptContextE — Ogre::parseColourOp(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseColourOp(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseColourOpERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceb4fc() -> ! {
    todo!("0xceb4fc __ZN4Ogre13parseColourOpERSsRNS_21MaterialScriptContextE")
}

// 0xceb6cc — __ZN4Ogre19parseAlphaRejectionERSsRNS_21MaterialScriptContextE — Ogre::parseAlphaRejection(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAlphaRejection(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre19parseAlphaRejectionERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceb6cc() -> ! {
    todo!("0xceb6cc __ZN4Ogre19parseAlphaRejectionERSsRNS_21MaterialScriptContextE")
}

// 0xcebaa8 — __ZN4Ogre20parseAlphaToCoverageERSsRNS_21MaterialScriptContextE — Ogre::parseAlphaToCoverage(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAlphaToCoverage(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre20parseAlphaToCoverageERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcebaa8() -> ! {
    todo!("0xcebaa8 __ZN4Ogre20parseAlphaToCoverageERSsRNS_21MaterialScriptContextE")
}

// 0xcebc2c — __ZN4Ogre23parseTransparentSortingERSsRNS_21MaterialScriptContextE — Ogre::parseTransparentSorting(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTransparentSorting(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre23parseTransparentSortingERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcebc2c() -> ! {
    todo!("0xcebc2c __ZN4Ogre23parseTransparentSortingERSsRNS_21MaterialScriptContextE")
}

// 0xcec348 — __ZN4Ogre15parseColourOpExERSsRNS_21MaterialScriptContextE — Ogre::parseColourOpEx(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseColourOpEx(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseColourOpExERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcec348() -> ! {
    todo!("0xcec348 __ZN4Ogre15parseColourOpExERSsRNS_21MaterialScriptContextE")
}

// 0xcecf28 — __ZN4Ogre21parseColourOpFallbackERSsRNS_21MaterialScriptContextE — Ogre::parseColourOpFallback(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseColourOpFallback(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre21parseColourOpFallbackERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcecf28() -> ! {
    todo!("0xcecf28 __ZN4Ogre21parseColourOpFallbackERSsRNS_21MaterialScriptContextE")
}

// 0xced384 — __ZN4Ogre14parseAlphaOpExERSsRNS_21MaterialScriptContextE — Ogre::parseAlphaOpEx(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAlphaOpEx(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseAlphaOpExERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xced384() -> ! {
    todo!("0xced384 __ZN4Ogre14parseAlphaOpExERSsRNS_21MaterialScriptContextE")
}

// 0xcede50 — __ZN4Ogre11parseEnvMapERSsRNS_21MaterialScriptContextE — Ogre::parseEnvMap(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseEnvMap(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre11parseEnvMapERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcede50() -> ! {
    todo!("0xcede50 __ZN4Ogre11parseEnvMapERSsRNS_21MaterialScriptContextE")
}

// 0xcee048 — __ZN4Ogre11parseScrollERSsRNS_21MaterialScriptContextE — Ogre::parseScroll(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseScroll(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre11parseScrollERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee048() -> ! {
    todo!("0xcee048 __ZN4Ogre11parseScrollERSsRNS_21MaterialScriptContextE")
}

// 0xcee354 — __ZN4Ogre15parseScrollAnimERSsRNS_21MaterialScriptContextE — Ogre::parseScrollAnim(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseScrollAnim(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseScrollAnimERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee354() -> ! {
    todo!("0xcee354 __ZN4Ogre15parseScrollAnimERSsRNS_21MaterialScriptContextE")
}

// 0xcee660 — __ZN4Ogre11parseRotateERSsRNS_21MaterialScriptContextE — Ogre::parseRotate(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseRotate(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre11parseRotateERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee660() -> ! {
    todo!("0xcee660 __ZN4Ogre11parseRotateERSsRNS_21MaterialScriptContextE")
}

// 0xcee684 — __ZN4Ogre15parseRotateAnimERSsRNS_21MaterialScriptContextE — Ogre::parseRotateAnim(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseRotateAnim(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseRotateAnimERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee684() -> ! {
    todo!("0xcee684 __ZN4Ogre15parseRotateAnimERSsRNS_21MaterialScriptContextE")
}

// 0xcee69c — __ZN4Ogre10parseScaleERSsRNS_21MaterialScriptContextE — Ogre::parseScale(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseScale(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre10parseScaleERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee69c() -> ! {
    todo!("0xcee69c __ZN4Ogre10parseScaleERSsRNS_21MaterialScriptContextE")
}

// 0xcee9a8 — __ZN4Ogre14parseWaveXformERSsRNS_21MaterialScriptContextE — Ogre::parseWaveXform(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseWaveXform(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseWaveXformERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcee9a8() -> ! {
    todo!("0xcee9a8 __ZN4Ogre14parseWaveXformERSsRNS_21MaterialScriptContextE")
}

// 0xceef54 — __ZN4Ogre14parseTransformERSsRNS_21MaterialScriptContextE — Ogre::parseTransform(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTransform(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseTransformERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xceef54() -> ! {
    todo!("0xceef54 __ZN4Ogre14parseTransformERSsRNS_21MaterialScriptContextE")
}

// 0xcef3e4 — __ZN4Ogre14parseDepthBiasERSsRNS_21MaterialScriptContextE — Ogre::parseDepthBias(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDepthBias(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseDepthBiasERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef3e4() -> ! {
    todo!("0xcef3e4 __ZN4Ogre14parseDepthBiasERSsRNS_21MaterialScriptContextE")
}

// 0xcef640 — __ZN4Ogre23parseIterationDepthBiasERSsRNS_21MaterialScriptContextE — Ogre::parseIterationDepthBias(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseIterationDepthBias(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre23parseIterationDepthBiasERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef640() -> ! {
    todo!("0xcef640 __ZN4Ogre23parseIterationDepthBiasERSsRNS_21MaterialScriptContextE")
}

// 0xcef874 — __ZN4Ogre15parseAnisotropyERSsRNS_21MaterialScriptContextE — Ogre::parseAnisotropy(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseAnisotropy(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseAnisotropyERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef874() -> ! {
    todo!("0xcef874 __ZN4Ogre15parseAnisotropyERSsRNS_21MaterialScriptContextE")
}

// 0xcef88c — __ZN4Ogre17parseTextureAliasERSsRNS_21MaterialScriptContextE — Ogre::parseTextureAlias(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTextureAlias(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseTextureAliasERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef88c() -> ! {
    todo!("0xcef88c __ZN4Ogre17parseTextureAliasERSsRNS_21MaterialScriptContextE")
}

// 0xcef8a0 — __ZN4Ogre15parseMipmapBiasERSsRNS_21MaterialScriptContextE — Ogre::parseMipmapBias(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseMipmapBias(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseMipmapBiasERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef8a0() -> ! {
    todo!("0xcef8a0 __ZN4Ogre15parseMipmapBiasERSsRNS_21MaterialScriptContextE")
}

// 0xcef8b4 — __ZN4Ogre16parseContentTypeERSsRNS_21MaterialScriptContextE — Ogre::parseContentType(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseContentType(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseContentTypeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcef8b4() -> ! {
    todo!("0xcef8b4 __ZN4Ogre16parseContentTypeERSsRNS_21MaterialScriptContextE")
}

// 0xcefe8c — __ZN4Ogre22parseIlluminationStageERSsRNS_21MaterialScriptContextE — Ogre::parseIlluminationStage(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseIlluminationStage(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre22parseIlluminationStageERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcefe8c() -> ! {
    todo!("0xcefe8c __ZN4Ogre22parseIlluminationStageERSsRNS_21MaterialScriptContextE")
}

// 0xcf0020 — __ZN4Ogre14parseLodValuesERSsRNS_21MaterialScriptContextE — Ogre::parseLodValues(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLodValues(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseLodValuesERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf0020() -> ! {
    todo!("0xcf0020 __ZN4Ogre14parseLodValuesERSsRNS_21MaterialScriptContextE")
}

// 0xcf02d8 — __ZN4Ogre13parseLodIndexERSsRNS_21MaterialScriptContextE — Ogre::parseLodIndex(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLodIndex(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseLodIndexERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf02d8() -> ! {
    todo!("0xcf02d8 __ZN4Ogre13parseLodIndexERSsRNS_21MaterialScriptContextE")
}

// 0xcf02f0 — __ZN4Ogre11parseSchemeERSsRNS_21MaterialScriptContextE — Ogre::parseScheme(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseScheme(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre11parseSchemeERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf02f0() -> ! {
    todo!("0xcf02f0 __ZN4Ogre11parseSchemeERSsRNS_21MaterialScriptContextE")
}

// 0xcf0304 — __ZN4Ogre18parseGPUVendorRuleERSsRNS_21MaterialScriptContextE — Ogre::parseGPUVendorRule(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseGPUVendorRule(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseGPUVendorRuleERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf0304() -> ! {
    todo!("0xcf0304 __ZN4Ogre18parseGPUVendorRuleERSsRNS_21MaterialScriptContextE")
}

// 0xcf08d0 — __ZN4Ogre18parseGPUDeviceRuleERSsRNS_21MaterialScriptContextE — Ogre::parseGPUDeviceRule(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseGPUDeviceRule(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseGPUDeviceRuleERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf08d0() -> ! {
    todo!("0xcf08d0 __ZN4Ogre18parseGPUDeviceRuleERSsRNS_21MaterialScriptContextE")
}

// 0xcf0d04 — __ZN4Ogre25parseShadowCasterMaterialERSsRNS_21MaterialScriptContextE — Ogre::parseShadowCasterMaterial(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowCasterMaterial(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre25parseShadowCasterMaterialERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf0d04() -> ! {
    todo!("0xcf0d04 __ZN4Ogre25parseShadowCasterMaterialERSsRNS_21MaterialScriptContextE")
}

// 0xcf0d18 — __ZN4Ogre27parseShadowReceiverMaterialERSsRNS_21MaterialScriptContextE — Ogre::parseShadowReceiverMaterial(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowReceiverMaterial(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre27parseShadowReceiverMaterialERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf0d18() -> ! {
    todo!("0xcf0d18 __ZN4Ogre27parseShadowReceiverMaterialERSsRNS_21MaterialScriptContextE")
}

// 0xcf0d2c — __ZN4Ogre20parseSetTextureAliasERSsRNS_21MaterialScriptContextE — Ogre::parseSetTextureAlias(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseSetTextureAlias(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre20parseSetTextureAliasERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf0d2c() -> ! {
    todo!("0xcf0d2c __ZN4Ogre20parseSetTextureAliasERSsRNS_21MaterialScriptContextE")
}

// 0xcf100c — __ZN4Ogre25processManualProgramParamEbSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmRKSs — Ogre::processManualProgramParam(bool,std::string,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> &,Ogre::MaterialScriptContext &,unsigned long,std::string const&)
#[doc(alias = "Ogre::processManualProgramParam(bool,std::string,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> &,Ogre::MaterialScriptContext &,unsigned long,std::string const&)")]
#[doc(alias = "__ZN4Ogre25processManualProgramParamEbSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmRKSs")]
pub fn stub_0xcf100c() -> ! {
    todo!("0xcf100c __ZN4Ogre25processManualProgramParamEbSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmRKSs")
}

// 0xcf1d14 — __ZN4Ogre23processAutoProgramParamEbRKSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmS1_ — Ogre::processAutoProgramParam(bool,std::string const&,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> &,Ogre::MaterialScriptContext &,unsigned long,std::string const&)
#[doc(alias = "Ogre::processAutoProgramParam(bool,std::string const&,std::vector<std::string,Ogre::STLAllocator<std::string,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>> &,Ogre::MaterialScriptContext &,unsigned long,std::string const&)")]
#[doc(alias = "__ZN4Ogre23processAutoProgramParamEbRKSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmS1_")]
pub fn stub_0xcf1d14() -> ! {
    todo!("0xcf1d14 __ZN4Ogre23processAutoProgramParamEbRKSsRSt6vectorISsNS_12STLAllocatorISsNS_22CategorisedAllocPolicyILNS_14MemoryCategoryE0EEEEEERNS_21MaterialScriptContextEmS1_")
}

// 0xcf25d0 — __ZN4Ogre17parseParamIndexedERSsRNS_21MaterialScriptContextE — Ogre::parseParamIndexed(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseParamIndexed(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseParamIndexedERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf25d0() -> ! {
    todo!("0xcf25d0 __ZN4Ogre17parseParamIndexedERSsRNS_21MaterialScriptContextE")
}

// 0xcf2980 — __ZN4Ogre21parseParamIndexedAutoERSsRNS_21MaterialScriptContextE — Ogre::parseParamIndexedAuto(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseParamIndexedAuto(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre21parseParamIndexedAutoERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf2980() -> ! {
    todo!("0xcf2980 __ZN4Ogre21parseParamIndexedAutoERSsRNS_21MaterialScriptContextE")
}

// 0xcf2d34 — __ZN4Ogre15parseParamNamedERSsRNS_21MaterialScriptContextE — Ogre::parseParamNamed(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseParamNamed(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre15parseParamNamedERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf2d34() -> ! {
    todo!("0xcf2d34 __ZN4Ogre15parseParamNamedERSsRNS_21MaterialScriptContextE")
}

// 0xcf3244 — __ZN4Ogre19parseParamNamedAutoERSsRNS_21MaterialScriptContextE — Ogre::parseParamNamedAuto(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseParamNamedAuto(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre19parseParamNamedAutoERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf3244() -> ! {
    todo!("0xcf3244 __ZN4Ogre19parseParamNamedAutoERSsRNS_21MaterialScriptContextE")
}

// 0xcf3754 — __ZN4Ogre13parseMaterialERSsRNS_21MaterialScriptContextE — Ogre::parseMaterial(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseMaterial(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre13parseMaterialERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf3754() -> ! {
    todo!("0xcf3754 __ZN4Ogre13parseMaterialERSsRNS_21MaterialScriptContextE")
}

// 0xcf4060 — __ZN4Ogre14parseTechniqueERSsRNS_21MaterialScriptContextE — Ogre::parseTechnique(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTechnique(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre14parseTechniqueERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf4060() -> ! {
    todo!("0xcf4060 __ZN4Ogre14parseTechniqueERSsRNS_21MaterialScriptContextE")
}

// 0xcf40f4 — __ZN4Ogre9parsePassERSsRNS_21MaterialScriptContextE — Ogre::parsePass(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parsePass(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre9parsePassERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf40f4() -> ! {
    todo!("0xcf40f4 __ZN4Ogre9parsePassERSsRNS_21MaterialScriptContextE")
}

// 0xcf4160 — __ZN4Ogre16parseTextureUnitERSsRNS_21MaterialScriptContextE — Ogre::parseTextureUnit(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTextureUnit(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseTextureUnitERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf4160() -> ! {
    todo!("0xcf4160 __ZN4Ogre16parseTextureUnitERSsRNS_21MaterialScriptContextE")
}

// 0xcf41ec — __ZN4Ogre21parseVertexProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre21parseVertexProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf41ec() -> ! {
    todo!("0xcf41ec __ZN4Ogre21parseVertexProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf46f4 — __ZN4Ogre23parseGeometryProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseGeometryProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseGeometryProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre23parseGeometryProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf46f4() -> ! {
    todo!("0xcf46f4 __ZN4Ogre23parseGeometryProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf4bfc — __ZN4Ogre33parseShadowCasterVertexProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseShadowCasterVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowCasterVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre33parseShadowCasterVertexProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf4bfc() -> ! {
    todo!("0xcf4bfc __ZN4Ogre33parseShadowCasterVertexProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf5084 — __ZN4Ogre35parseShadowCasterFragmentProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseShadowCasterFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowCasterFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre35parseShadowCasterFragmentProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf5084() -> ! {
    todo!("0xcf5084 __ZN4Ogre35parseShadowCasterFragmentProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf550c — __ZN4Ogre35parseShadowReceiverVertexProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseShadowReceiverVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowReceiverVertexProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre35parseShadowReceiverVertexProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf550c() -> ! {
    todo!("0xcf550c __ZN4Ogre35parseShadowReceiverVertexProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf5994 — __ZN4Ogre37parseShadowReceiverFragmentProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseShadowReceiverFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseShadowReceiverFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre37parseShadowReceiverFragmentProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf5994() -> ! {
    todo!("0xcf5994 __ZN4Ogre37parseShadowReceiverFragmentProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf5e1c — __ZN4Ogre23parseFragmentProgramRefERSsRNS_21MaterialScriptContextE — Ogre::parseFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseFragmentProgramRef(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre23parseFragmentProgramRefERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf5e1c() -> ! {
    todo!("0xcf5e1c __ZN4Ogre23parseFragmentProgramRefERSsRNS_21MaterialScriptContextE")
}

// 0xcf6320 — __ZN4Ogre18parseVertexProgramERSsRNS_21MaterialScriptContextE — Ogre::parseVertexProgram(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseVertexProgram(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseVertexProgramERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6320() -> ! {
    todo!("0xcf6320 __ZN4Ogre18parseVertexProgramERSsRNS_21MaterialScriptContextE")
}

// 0xcf6684 — __ZN4Ogre20parseGeometryProgramERSsRNS_21MaterialScriptContextE — Ogre::parseGeometryProgram(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseGeometryProgram(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre20parseGeometryProgramERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6684() -> ! {
    todo!("0xcf6684 __ZN4Ogre20parseGeometryProgramERSsRNS_21MaterialScriptContextE")
}

// 0xcf69ec — __ZN4Ogre20parseFragmentProgramERSsRNS_21MaterialScriptContextE — Ogre::parseFragmentProgram(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseFragmentProgram(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre20parseFragmentProgramERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf69ec() -> ! {
    todo!("0xcf69ec __ZN4Ogre20parseFragmentProgramERSsRNS_21MaterialScriptContextE")
}

// 0xcf6d50 — __ZN4Ogre18parseProgramSourceERSsRNS_21MaterialScriptContextE — Ogre::parseProgramSource(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramSource(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseProgramSourceERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6d50() -> ! {
    todo!("0xcf6d50 __ZN4Ogre18parseProgramSourceERSsRNS_21MaterialScriptContextE")
}

// 0xcf6d64 — __ZN4Ogre29parseProgramSkeletalAnimationERSsRNS_21MaterialScriptContextE — Ogre::parseProgramSkeletalAnimation(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramSkeletalAnimation(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre29parseProgramSkeletalAnimationERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6d64() -> ! {
    todo!("0xcf6d64 __ZN4Ogre29parseProgramSkeletalAnimationERSsRNS_21MaterialScriptContextE")
}

// 0xcf6d78 — __ZN4Ogre26parseProgramMorphAnimationERSsRNS_21MaterialScriptContextE — Ogre::parseProgramMorphAnimation(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramMorphAnimation(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre26parseProgramMorphAnimationERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6d78() -> ! {
    todo!("0xcf6d78 __ZN4Ogre26parseProgramMorphAnimationERSsRNS_21MaterialScriptContextE")
}

// 0xcf6d8c — __ZN4Ogre25parseProgramPoseAnimationERSsRNS_21MaterialScriptContextE — Ogre::parseProgramPoseAnimation(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramPoseAnimation(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre25parseProgramPoseAnimationERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6d8c() -> ! {
    todo!("0xcf6d8c __ZN4Ogre25parseProgramPoseAnimationERSsRNS_21MaterialScriptContextE")
}

// 0xcf6da0 — __ZN4Ogre30parseProgramVertexTextureFetchERSsRNS_21MaterialScriptContextE — Ogre::parseProgramVertexTextureFetch(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramVertexTextureFetch(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre30parseProgramVertexTextureFetchERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6da0() -> ! {
    todo!("0xcf6da0 __ZN4Ogre30parseProgramVertexTextureFetchERSsRNS_21MaterialScriptContextE")
}

// 0xcf6db4 — __ZN4Ogre18parseProgramSyntaxERSsRNS_21MaterialScriptContextE — Ogre::parseProgramSyntax(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseProgramSyntax(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseProgramSyntaxERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6db4() -> ! {
    todo!("0xcf6db4 __ZN4Ogre18parseProgramSyntaxERSsRNS_21MaterialScriptContextE")
}

// 0xcf6dd0 — __ZN4Ogre18parseTextureSourceERSsRNS_21MaterialScriptContextE — Ogre::parseTextureSource(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTextureSource(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseTextureSourceERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf6dd0() -> ! {
    todo!("0xcf6dd0 __ZN4Ogre18parseTextureSourceERSsRNS_21MaterialScriptContextE")
}

// 0xcf7738 — __ZN4Ogre19parseReceiveShadowsERSsRNS_21MaterialScriptContextE — Ogre::parseReceiveShadows(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseReceiveShadows(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre19parseReceiveShadowsERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf7738() -> ! {
    todo!("0xcf7738 __ZN4Ogre19parseReceiveShadowsERSsRNS_21MaterialScriptContextE")
}

// 0xcf78b4 — __ZN4Ogre18parseDefaultParamsERSsRNS_21MaterialScriptContextE — Ogre::parseDefaultParams(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseDefaultParams(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre18parseDefaultParamsERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf78b4() -> ! {
    todo!("0xcf78b4 __ZN4Ogre18parseDefaultParamsERSsRNS_21MaterialScriptContextE")
}

// 0xcf78bc — __ZN4Ogre29parseTransparencyCastsShadowsERSsRNS_21MaterialScriptContextE — Ogre::parseTransparencyCastsShadows(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseTransparencyCastsShadows(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre29parseTransparencyCastsShadowsERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf78bc() -> ! {
    todo!("0xcf78bc __ZN4Ogre29parseTransparencyCastsShadowsERSsRNS_21MaterialScriptContextE")
}

// 0xcf7a38 — __ZN4Ogre16parseLodStrategyERSsRNS_21MaterialScriptContextE — Ogre::parseLodStrategy(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLodStrategy(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre16parseLodStrategyERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf7a38() -> ! {
    todo!("0xcf7a38 __ZN4Ogre16parseLodStrategyERSsRNS_21MaterialScriptContextE")
}

// 0xcf7b8c — __ZN4Ogre17parseLodDistancesERSsRNS_21MaterialScriptContextE — Ogre::parseLodDistances(std::string &,Ogre::MaterialScriptContext &)
#[doc(alias = "Ogre::parseLodDistances(std::string &,Ogre::MaterialScriptContext &)")]
#[doc(alias = "__ZN4Ogre17parseLodDistancesERSsRNS_21MaterialScriptContextE")]
pub fn stub_0xcf7b8c() -> ! {
    todo!("0xcf7b8c __ZN4Ogre17parseLodDistancesERSsRNS_21MaterialScriptContextE")
}

// 0xd0168c — __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_ — std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)> const&)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert_unique(std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)> const&)")]
#[doc(alias = "__ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_")]
pub fn stub_0xd0168c() -> ! {
    todo!("0xd0168c __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE16_M_insert_uniqueERKS8_")
}

// 0xd01770 — __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKS8_ — std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert(std::_Rb_tree_node_base *,std::_Rb_tree_node_base *,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)> const&)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_insert(std::_Rb_tree_node_base *,std::_Rb_tree_node_base *,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)> const&)")]
#[doc(alias = "__ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKS8_")]
pub fn stub_0xd01770() -> ! {
    todo!("0xd01770 __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE9_M_insertEPSt18_Rb_tree_node_baseSK_RKS8_")
}

// 0xd018d4 — __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED1Ev — std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_Rb_tree_impl<std::less<std::string>,false>::~_Rb_tree_impl()
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_Rb_tree_impl<std::less<std::string>,false>::~_Rb_tree_impl()")]
#[doc(alias = "__ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED1Ev")]
pub fn stub_0xd018d4() -> ! {
    todo!("0xd018d4 __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED1Ev")
}

// 0xd018d8 — __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED0Ev — std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_Rb_tree_impl<std::less<std::string>,false>::~_Rb_tree_impl()
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_Rb_tree_impl<std::less<std::string>,false>::~_Rb_tree_impl()")]
#[doc(alias = "__ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED0Ev")]
pub fn stub_0xd018d8() -> ! {
    todo!("0xd018d8 __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE13_Rb_tree_implISC_Lb0EED0Ev")
}

// 0xd018e8 — __ZN4Ogre21MaterialScriptContextD2Ev — Ogre::MaterialScriptContext::~MaterialScriptContext()
#[doc(alias = "Ogre::MaterialScriptContext::~MaterialScriptContext()")]
#[doc(alias = "__ZN4Ogre21MaterialScriptContextD2Ev")]
pub fn stub_0xd018e8() -> ! {
    todo!("0xd018e8 __ZN4Ogre21MaterialScriptContextD2Ev")
}

// 0xd01bc0 — __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS8_E — std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>> *)
#[doc(alias = "std::_Rb_tree<std::string,std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,std::_Select1st<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>>,std::less<std::string>,Ogre::STLAllocator<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>,Ogre::CategorisedAllocPolicy<(Ogre::MemoryCategory)0>>>::_M_erase(std::_Rb_tree_node<std::pair<std::string const,bool (*)(std::string &,Ogre::MaterialScriptContext &)>> *)")]
#[doc(alias = "__ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS8_E")]
pub fn stub_0xd01bc0() -> ! {
    todo!("0xd01bc0 __ZNSt8_Rb_treeISsSt4pairIKSsPFbRSsRN4Ogre21MaterialScriptContextEEESt10_Select1stIS8_ESt4lessISsENS3_12STLAllocatorIS8_NS3_22CategorisedAllocPolicyILNS3_14MemoryCategoryE0EEEEEE8_M_eraseEPSt13_Rb_tree_nodeIS8_E")
}
