[package]
name = "rbx-datamodel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
bitflags.workspace = true

rbx-core = { path = "../core" }
rbx-reflection = { path = "../reflection" }
